import CMetaCFlowCalculus.CFlow.MachineSchema

namespace CMetaCFlowCalculus.CFlow.MachineSchemaHeader

private def continuation : String :=
  " " ++ String.singleton '\\' ++ String.singleton '\n'

private def renderRows : List (MachineEnumRow α) → String
  | [] => ""
  | [row] => "    X(" ++ row.cName ++ ", " ++ toString row.value ++ ")\n"
  | row :: rest =>
      "    X(" ++ row.cName ++ ", " ++ toString row.value ++ ")" ++
        continuation ++ renderRows rest

private def renderListMacro (name : String)
    (rows : List (MachineEnumRow α)) : String :=
  "#define " ++ name ++ "(X)" ++ continuation ++ renderRows rows

private def renderValidated : String :=
  "#ifndef CFLOW_GENERATED_MACHINE_SCHEMA_H\n" ++
  "#define CFLOW_GENERATED_MACHINE_SCHEMA_H\n\n" ++
  "/* Generated by cflow-machine-schema-gen. Do not edit by hand. */\n\n" ++
  "#define CFLOW_MACHINE_SCHEMA_VERSION " ++ toString machineSchemaVersion ++ "u\n\n" ++
  renderListMacro "CFLOW_MACHINE_STATE_KIND_ROWS" stateKindRows ++ "\n" ++
  renderListMacro "CFLOW_MACHINE_ACTION_OBSERVATION_ROWS" actionObservationRows ++ "\n" ++
  "#define CFLOW_MACHINE_STATE_KIND_COUNT " ++ toString stateKindRows.length ++ "u\n" ++
  "#define CFLOW_MACHINE_ACTION_OBSERVATION_COUNT " ++
    toString actionObservationRows.length ++ "u\n\n" ++
  "#endif /* CFLOW_GENERATED_MACHINE_SCHEMA_H */\n"

def render : Except MachineSchemaError String :=
  match MachineSchema.validate with
  | .error failure => .error failure
  | .ok () => .ok renderValidated

end CMetaCFlowCalculus.CFlow.MachineSchemaHeader
