import CMetaCFlowCalculus.CFlow.OperatorPolicyManifest

namespace CMetaCFlowCalculus.CFlow.OperatorPolicyHeader

open CMeta

private def rowName (token : String) : String :=
  "CMETA_ROW_" ++ token

private def renderRows : List String → String
  | [] => ""
  | [row] => "    " ++ row ++ "\n"
  | row :: rest => "    " ++ row ++ ", \\\n" ++ renderRows rest

private def renderListMacro (name : String) (rows : List String) : String :=
  "#define " ++ name ++ " \\\n" ++ renderRows rows

private def renderUnary (relation : UnaryRelation) : String :=
  "CMETA_U_ID(" ++ rowName relation.input ++ ", " ++
    rowName relation.output ++ ")"

private def renderBinary (relation : BinaryRelation) : String :=
  "CMETA_B_ID(" ++ rowName relation.left ++ ", " ++
    rowName relation.right ++ ", " ++ rowName relation.output ++ ")"

private def renderGenerator (relation : GeneratorRelation) : String :=
  "CMETA_G_ID(" ++ rowName relation.input ++ ", " ++
    rowName relation.output ++ ")"

private def renderValidated (policy : OperatorPolicyManifest) : String :=
  "#ifndef CFLOW_GENERATED_BUILTIN_OPERATOR_POLICY_H\n" ++
  "#define CFLOW_GENERATED_BUILTIN_OPERATOR_POLICY_H\n\n" ++
  "/* Generated by cflow-operator-policy-gen. Do not edit by hand. */\n\n" ++
  renderListMacro "CFLOW_BUILTIN_FILTER_SIGNATURE_LIST"
    (policy.filter.map renderUnary) ++ "\n" ++
  renderListMacro "CFLOW_BUILTIN_MAP_SIGNATURE_LIST"
    (policy.map.map renderUnary) ++ "\n" ++
  renderListMacro "CFLOW_BUILTIN_TRANSFORM_SIGNATURE_LIST"
    (policy.transform.map renderUnary) ++ "\n" ++
  renderListMacro "CFLOW_BUILTIN_FLAT_MAP_SIGNATURE_LIST"
    (policy.flatMap.map renderGenerator) ++ "\n" ++
  renderListMacro "CFLOW_BUILTIN_REDUCE_SIGNATURE_LIST"
    (policy.reduce.map renderBinary) ++ "\n" ++
  renderListMacro "CFLOW_BUILTIN_ZIP_SIGNATURE_LIST"
    (policy.zip.map renderBinary) ++ "\n" ++
  "#define CFLOW_BUILTIN_FILTER_SIGNATURE_COUNT " ++
    toString policy.filter.length ++ "u\n" ++
  "#define CFLOW_BUILTIN_MAP_SIGNATURE_COUNT " ++
    toString policy.map.length ++ "u\n" ++
  "#define CFLOW_BUILTIN_TRANSFORM_SIGNATURE_COUNT " ++
    toString policy.transform.length ++ "u\n" ++
  "#define CFLOW_BUILTIN_FLAT_MAP_SIGNATURE_COUNT " ++
    toString policy.flatMap.length ++ "u\n" ++
  "#define CFLOW_BUILTIN_REDUCE_SIGNATURE_COUNT " ++
    toString policy.reduce.length ++ "u\n" ++
  "#define CFLOW_BUILTIN_ZIP_SIGNATURE_COUNT " ++
    toString policy.zip.length ++ "u\n\n" ++
  "#endif /* CFLOW_GENERATED_BUILTIN_OPERATOR_POLICY_H */\n"

def render (registry : SignatureManifest)
    (policy : OperatorPolicyManifest) : Except OperatorPolicyError String :=
  match policy.validate registry with
  | .error failure => .error failure
  | .ok () => .ok (renderValidated policy)

end CMetaCFlowCalculus.CFlow.OperatorPolicyHeader
