#ifndef CSERDE_STATUS_H
#define CSERDE_STATUS_H

typedef enum cserde_status {
    CSERDE_OK = 0,
    CSERDE_DONE,
    CSERDE_INVALID_ARGUMENT,
    CSERDE_INVALID_STATE,
    CSERDE_INVALID_TOKEN,
    CSERDE_UNEXPECTED_END,
    CSERDE_VALUE_OUT_OF_RANGE,
    CSERDE_LIMIT_EXCEEDED,
    CSERDE_UNSUPPORTED,
    CSERDE_SOURCE_ERROR,
    CSERDE_SINK_ERROR,
    CSERDE_CALLBACK_ERROR
} cserde_status;

#endif /* CSERDE_STATUS_H */
