#include <cmeta/meta.h>
#include <cflow/scheduler.h>
#include <cflow/runtime.h>

#include <assert.h>
#include <stdio.h>
#include <string.h>

enum {
    COUNTER_CAP_RESET = 1u << 0
};

#define COUNTER_METHODS(X,I) \
    X(I,R1,int,add,int,delta) \
    X(I,R0,int,value,_) \
    X(I,V0,void,reset,_)

interface(counter, COUNTER_METHODS);

typedef struct counter_state {
    int value;
} counter_state;

static int basic_add(void *self, int delta) {
    counter_state *s = (counter_state *)self;
    s->value += delta;
    return s->value;
}
static int basic_value(void *self) {
    return ((counter_state *)self)->value;
}
static void basic_reset(void *self) {
    ((counter_state *)self)->value = 0;
}

implements(counter, basic_counter, COUNTER_CAP_RESET,
    .add = basic_add,
    .value = basic_value,
    .reset = basic_reset
);

interface_impl(counter, COUNTER_METHODS)

int main(void) {
    counter_state state = { 4 };
    counter c = basic_counter_as_counter(&state);

    assert(counter_valid(&c));
    assert(strcmp(counter_implementation(&c), "basic_counter") == 0);
    assert(counter_has(&c, COUNTER_CAP_RESET));
    assert(counter_add(&c, 3) == 7);
    assert(counter_value(&c) == 7);
    counter_reset(&c);
    assert(counter_value(&c) == 0);

    const cmeta_interface_desc *meta = counter_interface();
    assert(meta && strcmp(meta->name, "counter") == 0);
    assert(meta->method_count == 3);
    assert(strcmp(meta->methods[0].name, "add") == 0 && meta->methods[0].arity == 1);
    assert(strcmp(meta->methods[1].name, "value") == 0 && meta->methods[1].arity == 0);
    assert(strcmp(meta->methods[2].name, "reset") == 0 && meta->methods[2].arity == 0);

    /* CFlow boundary interfaces are generated by the same CMeta protocol. */
    assert(cflow_scheduler_interface()->method_count == 10);
    assert(cflow_source_interface()->method_count == 7);
    assert(cflow_waitable_interface()->method_count == 2);
    assert(cflow_sink_interface()->method_count == 3);

    puts("interface/implements: generated handle, vtable, wrappers, capabilities, metadata");
    puts("CFlow boundaries: Scheduler / Source / Waitable / Sink use the same protocol");
    return 0;
}
