#ifndef SALTS_PLUGIN_LINKER_FIXTURE_H
#define SALTS_PLUGIN_LINKER_FIXTURE_H

enum {
    PLUGIN_LINKER_EXPORT_COUNT = 3u,
    PLUGIN_LINKER_PROVIDER_COUNT = 2u,
    PLUGIN_LINKER_INPUT = 7,
    PLUGIN_LINKER_BIAS = 7
};

#endif
