# Verify that one production CNet DSO owns both manager/handoff identities.
if(TARGET cnet_manager OR TARGET Salts::CNetManager)
  message(FATAL_ERROR "Legacy Salts::CNetManager target is forbidden")
endif()
if(NOT TARGET cnet OR NOT TARGET Salts::CNet)
  message(FATAL_ERROR "Canonical production Salts::CNet is required")
endif()
get_target_property(_cnet_sources cnet SOURCES)
foreach(_file IN ITEMS cnet_manager.c cnet_handoff.c)
  set(_count 0)
  foreach(_source IN LISTS _cnet_sources)
    get_filename_component(_name "${_source}" NAME)
    if(_name STREQUAL _file)
      math(EXPR _count "${_count}+1")
    endif()
  endforeach()
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "${_file} must occur exactly once in production CNet")
  endif()
  foreach(_profile IN ITEMS cnet_profile cnet_test_profile)
    if(TARGET ${_profile})
      get_target_property(_sources ${_profile} SOURCES)
      foreach(_source IN LISTS _sources)
        get_filename_component(_name "${_source}" NAME)
        if(_name STREQUAL _file)
          message(FATAL_ERROR "${_profile} must not duplicate ${_file}")
        endif()
      endforeach()
    endif()
  endforeach()
endforeach()
get_target_property(_links cnet INTERFACE_LINK_LIBRARIES)
foreach(_dep IN LISTS _links)
  if(_dep MATCHES "Salts::(CFlow|CNetManager)")
    message(FATAL_ERROR "CNet acquired unwanted dependency: ${_dep}")
  endif()
endforeach()
unset(_cnet_sources)
unset(_file)
unset(_count)
unset(_source)
unset(_name)
unset(_profile)
unset(_sources)
unset(_links)
unset(_dep)
