import Std

/-! GENERATED by formal/cmeta_conformance_gen.c from CMeta/CFlow headers. -/

namespace CMeta.CGenerated

structure OperatorSchemaRow where
  enumName : String
  method : String
  methodArgc : Nat
  fnArg : Int
  subgraphArg : Int
  fnArity : Nat
  p0 : String
  p1 : String
  p2 : String
  ret : String
  output : String
  cardinality : String
  subgraphRule : String
  semantic : String
  effects : String
  deriving Repr, DecidableEq

def builtinTypeTokens : List String :=
  "B" ::
  "I" ::
  "L" ::
  "F" ::
  "D" ::
  []

def filterPolicyIds : List String :=
  "U_I_B" ::
  []

def mapPolicyIds : List String :=
  "U_I_I" ::
  "U_I_L" ::
  "U_L_D" ::
  "U_D_I" ::
  "U_I_D" ::
  "U_I_F" ::
  "U_F_D" ::
  []

def transformPolicyIds : List String :=
  "U_I_L" ::
  []

def flatMapPolicyIds : List String :=
  "G_I_L" ::
  []

def reducePolicyIds : List String :=
  "B_L_L_L" ::
  []

def zipPolicyIds : List String :=
  "B_L_D_D" ::
  []

def operatorSchemas : List OperatorSchemaRow :=
  { enumName := "FILTER", method := "filter", methodArgc := 1, fnArg := 0, subgraphArg := -1, fnArity := 1, p0 := "INPUT", p1 := "NONE", p2 := "NONE", ret := "BOOL", output := "SAME", cardinality := "FILTER", subgraphRule := "NONE", semantic := "filter", effects := "CMETA_EFFECT_PURE" } ::
  { enumName := "MAP", method := "map", methodArgc := 1, fnArg := 0, subgraphArg := -1, fnArity := 1, p0 := "INPUT", p1 := "NONE", p2 := "NONE", ret := "VALUE", output := "RETURN", cardinality := "ONE", subgraphRule := "NONE", semantic := "map", effects := "CMETA_EFFECT_PURE" } ::
  { enumName := "TRANSFORM", method := "transform", methodArgc := 1, fnArg := 0, subgraphArg := -1, fnArity := 1, p0 := "INPUT", p1 := "NONE", p2 := "NONE", ret := "VALUE", output := "RETURN", cardinality := "ONE", subgraphRule := "NONE", semantic := "map", effects := "CMETA_EFFECT_PURE" } ::
  { enumName := "FLAT_MAP", method := "flatMap", methodArgc := 1, fnArg := 0, subgraphArg := -1, fnArity := 3, p0 := "INPUT", p1 := "OUT_PTR", p2 := "CURSOR", ret := "GENERATOR", output := "POINTEE1", cardinality := "EXPAND", subgraphRule := "NONE", semantic := "flat_map", effects := "CMETA_EFFECT_PURE" } ::
  { enumName := "REDUCE", method := "reduce", methodArgc := 1, fnArg := 0, subgraphArg := -1, fnArity := 2, p0 := "INPUT", p1 := "INPUT", p2 := "NONE", ret := "INPUT", output := "SAME", cardinality := "REDUCE", subgraphRule := "NONE", semantic := "reduce", effects := "CMETA_EFFECT_STATEFUL" } ::
  { enumName := "ZIP", method := "zip", methodArgc := 2, fnArg := 1, subgraphArg := 0, fnArity := 2, p0 := "INPUT", p1 := "SUBGRAPH", p2 := "NONE", ret := "VALUE", output := "RETURN", cardinality := "ONE", subgraphRule := "SUBGRAPH_1TO1", semantic := "high_level", effects := "CMETA_EFFECT_PURE" } ::
  []

end CMeta.CGenerated
