import Std

/-! GENERATED by formal/cmeta_optimizer_topology_conformance_gen.c using real CFlow reachability optimization/runtime. -/

namespace CMeta.COptimizerTopologyGenerated

structure TopologyWitness where
  name : String
  beforeSubgraphs : Nat
  beforeReachable : Nat
  deadOnSubgraphs : Nat
  deadOnReachable : Nat
  deadOnRemoved : Nat
  deadOffSubgraphs : Nat
  deadOffReachable : Nat
  deadOffRemoved : Nat
  reachableBranchRetainedOn : Bool
  reachableBranchRetainedOff : Bool
  input : List Int
  beforeOutput : List Int
  deadOnOutput : List Int
  deadOffOutput : List Int
  deriving Repr, DecidableEq

def topologyWitnesses : List TopologyWitness :=
  { name := "dead_subgraph_reachability_i_l",
    beforeSubgraphs := 3, beforeReachable := 2,
    deadOnSubgraphs := 2, deadOnReachable := 2, deadOnRemoved := 1,
    deadOffSubgraphs := 3, deadOffReachable := 2, deadOffRemoved := 0,
    reachableBranchRetainedOn := true, reachableBranchRetainedOff := true,
    input := [-2, 0, 3],
    beforeOutput := [-4, 0, 6],
    deadOnOutput := [-4, 0, 6],
    deadOffOutput := [-4, 0, 6] } ::
  []

end CMeta.COptimizerTopologyGenerated
