import Std

/-! GENERATED by formal/cmeta_optimizer_conformance_gen.c using the real CFlow optimizer/runtime. -/

namespace CMeta.COptimizerGenerated

structure OptimizerWitness where
  name : String
  inputType : String
  outputType : String
  nodesBefore : Nat
  nodesAfter : Nat
  mapNodesFused : Nat
  fnChainCount : Nat
  idempotentEliminated : Nat
  propertyBlocked : Nat
  input : List Int
  before : List Int
  after : List Int
  deriving Repr, DecidableEq

def optimizerWitnesses : List OptimizerWitness :=
  { name := "duplicate_idempotent_identity_i", inputType := "I", outputType := "I",
    nodesBefore := 3, nodesAfter := 2, mapNodesFused := 1,
    fnChainCount := 1, idempotentEliminated := 1, propertyBlocked := 0,
    input := [-2, 0, 3], before := [-2, 0, 3], after := [-2, 0, 3] } ::
  { name := "duplicate_plain_identity_i", inputType := "I", outputType := "I",
    nodesBefore := 3, nodesAfter := 2, mapNodesFused := 1,
    fnChainCount := 2, idempotentEliminated := 0, propertyBlocked := 1,
    input := [-2, 0, 3], before := [-2, 0, 3], after := [-2, 0, 3] } ::
  []

end CMeta.COptimizerGenerated
