import Std

/-! GENERATED by formal/cmeta_optimizer_gating_conformance_gen.c using real opt.c gates. -/

namespace CMeta.COptimizerGatingGenerated

structure MapEffectWitness where
  name : String
  input : List Int
  firstPure : Bool
  secondPure : Bool
  nodesBefore : Nat
  nodesAfter : Nat
  mapNodesFused : Nat
  effectBlocked : Nat
  before : List Int
  after : List Int
  deriving Repr, DecidableEq

structure RelationGateWitness where
  name : String
  input : List Int
  isPure : Bool
  isStable : Bool
  beforeCoordination : String
  afterCoordination : String
  simplified : Nat
  effectBlocked : Nat
  propertyBlocked : Nat
  before : List Int
  after : List Int
  deriving Repr, DecidableEq

def mapEffectWitnesses : List MapEffectWitness :=
  { name := "impure_map_blocks_fusion", input := [-2, 0, 3], firstPure := false, secondPure := true,
    nodesBefore := 3, nodesAfter := 3, mapNodesFused := 0, effectBlocked := 1,
    before := [-2, 2, 8], after := [-2, 2, 8] } ::
  []

def relationGateWitnesses : List RelationGateWitness :=
  { name := "relation_pure_stable_simplifies", input := [-2, 0, 3], isPure := true, isStable := true,
    beforeCoordination := "SEQUENCE", afterCoordination := "ANY",
    simplified := 1, effectBlocked := 0, propertyBlocked := 0,
    before := [-6, 0, 9], after := [-6, 0, 9] } ::
  { name := "relation_pure_unstable_blocks", input := [-2, 0, 3], isPure := true, isStable := false,
    beforeCoordination := "SEQUENCE", afterCoordination := "SEQUENCE",
    simplified := 0, effectBlocked := 0, propertyBlocked := 1,
    before := [-6, 0, 9], after := [-6, 0, 9] } ::
  { name := "relation_impure_stable_blocks", input := [-2, 0, 3], isPure := false, isStable := true,
    beforeCoordination := "SEQUENCE", afterCoordination := "SEQUENCE",
    simplified := 0, effectBlocked := 1, propertyBlocked := 0,
    before := [-6, 0, 9], after := [-6, 0, 9] } ::
  []

end CMeta.COptimizerGatingGenerated
