import Std

/-! GENERATED by formal/cmeta_plan_conformance_gen.c using the real CFlow plan compiler. -/

namespace CMeta.CPlanGenerated

structure PlanInstRow where
  opcode : String
  input : String
  output : String
  callbacks : List String
  deriving Repr, DecidableEq

structure PlanWitness where
  name : String
  input : String
  output : String
  code : List PlanInstRow
  deriving Repr, DecidableEq

def witnesses : List PlanWitness :=
  { name := "filter_i", input := "I", output := "I", code := [
    { opcode := "FILTER", input := "I", output := "I", callbacks := ["U_I_B"] }
  ] } ::
  { name := "map_i_l", input := "I", output := "L", code := [
    { opcode := "MAP", input := "I", output := "L", callbacks := ["U_I_L"] }
  ] } ::
  { name := "transform_i_l", input := "I", output := "L", code := [
    { opcode := "MAP", input := "I", output := "L", callbacks := ["U_I_L"] }
  ] } ::
  { name := "fused_map_i_l_d", input := "I", output := "D", code := [
    { opcode := "MAP", input := "I", output := "D", callbacks := ["U_I_L", "U_L_D"] }
  ] } ::
  { name := "flat_map_i_l", input := "I", output := "L", code := [
    { opcode := "FLAT_MAP", input := "I", output := "L", callbacks := ["G_I_L"] }
  ] } ::
  { name := "reduce_l", input := "L", output := "L", code := [
    { opcode := "REDUCE", input := "L", output := "L", callbacks := ["B_L_L_L"] }
  ] } ::
  []

end CMeta.CPlanGenerated
