import CMeta.PreprocessorBackendRegistryMutation
import CMeta.PreprocessorBackendRegistryEquivalence
import CMeta.PreprocessorBackendRegistrySubstitutability
import CMeta.PreprocessorBackendRegistrySetoid

#check CMeta.Producer.PreprocessorBackendRegistry.observe
#check CMeta.Producer.PreprocessorBackendRegistry.Equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.registrySetoid
#check CMeta.Producer.PreprocessorBackendRegistry.MutationResultEquivalent

assert_not_exists CMeta.Producer.PreprocessorBackendRegistry.observe_insert_self
assert_not_exists CMeta.Producer.PreprocessorBackendRegistry.observe_insert_ne
assert_not_exists CMeta.Producer.PreprocessorBackendRegistry.observe_remove
assert_not_exists CMeta.Producer.PreprocessorBackendRegistry.observe_replace_self
assert_not_exists CMeta.Producer.PreprocessorBackendRegistry.observe_replace_ne

-- TEMP-MODULE-BRIDGE(M7f): legacy LanguageSpec equality rules
#check CMeta.Producer.PreprocessorBackendRegistry.equivalent_refl
#check CMeta.Producer.PreprocessorBackendRegistry.equivalent_symm
#check CMeta.Producer.PreprocessorBackendRegistry.equivalent_trans

-- TEMP-MODULE-BRIDGE(M7g): legacy mutation/equivalence conformance
#check CMeta.Producer.PreprocessorBackendRegistry.supportingCandidates_insert_irrelevant
#check CMeta.Producer.PreprocessorBackendRegistry.selectSupporting_insert_irrelevant
#check CMeta.Producer.PreprocessorBackendRegistry.remove_missing_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.insert_remove_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.remove_remove_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.replace_last_write_wins
#check CMeta.Producer.PreprocessorBackendRegistry.supportingCandidates_perm_of_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.selectSupporting_key_eq_of_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.selectSupporting_lowering_eq_of_equivalent
#check CMeta.Producer.PreprocessorBackendRegistry.observe_congr
#check CMeta.Producer.PreprocessorBackendRegistry.supportingCandidates_congr
#check CMeta.Producer.PreprocessorBackendRegistry.selectSupporting_key_congr
#check CMeta.Producer.PreprocessorBackendRegistry.selectSupporting_lowering_congr
#check CMeta.Producer.PreprocessorBackendRegistry.remove_congr
#check CMeta.Producer.PreprocessorBackendRegistry.insert_congr
#check CMeta.Producer.PreprocessorBackendRegistry.replace_congr
