module
import Std

/-! GENERATED by formal/cmeta_structured_policy_conformance_gen.c using the real CFlow relation policies. -/

namespace CMeta.CStructuredPolicyGenerated

structure PolicyWitness where
  name : String
  inputType : String
  outputType : String
  coordination : String
  completion : String
  result : String
  error : String
  branchCount : Nat
  reducer : String
  input : List Int
  count : Nat
  output : List Int
  directPlanAccepted : Bool
  deriving Repr, DecidableEq

def policyWitnesses : List PolicyWitness :=
  { name := "relation_latest_fold_i_l", inputType := "I", outputType := "L",
    coordination := "LATEST", completion := "COORDINATOR", result := "FOLD",
    error := "FAIL_FAST", branchCount := 2, reducer := "B_L_L_L", input := [-2, 0, 3], count := 9,
    output := [-22, -21, 79, 0, 1, 101, 33, 34, 134], directPlanAccepted := false } ::
  { name := "relation_any_ignore_i_l", inputType := "I", outputType := "L",
    coordination := "ANY", completion := "COORDINATOR", result := "SELECT",
    error := "IGNORE", branchCount := 2, reducer := "", input := [-2, 0, 3], count := 3,
    output := [-20, 0, 30], directPlanAccepted := false } ::
  { name := "relation_fallback_try_next_i_l", inputType := "I", outputType := "L",
    coordination := "SEQUENCE", completion := "FIRST_RESULT", result := "SELECT",
    error := "TRY_NEXT", branchCount := 2, reducer := "", input := [-2, 0, 3], count := 3,
    output := [-20, 0, 30], directPlanAccepted := false } ::
  []

end CMeta.CStructuredPolicyGenerated
