#ifndef TURBO_STL_STATUS_H
#define TURBO_STL_STATUS_H

typedef enum turbostl_status {
  TURBO_STL_OK = 0,
  TURBO_STL_INVALID_ARGUMENT,
  TURBO_STL_OUT_OF_MEMORY,
  TURBO_STL_CAPACITY_EXCEEDED,
  TURBO_STL_EMPTY,
  TURBO_STL_NOT_FOUND,
  TURBO_STL_TYPE_MISMATCH,
  TURBO_STL_TRAIT_MISSING
} turbostl_status;

#endif /* TURBO_STL_STATUS_H */
