add_executable(cmeta_plan_conformance_gen EXCLUDE_FROM_ALL
  cmeta_plan_conformance_gen.c)

target_compile_features(cmeta_plan_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_plan_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_plan_conformance_gen PROPERTIES FOLDER "formal")

add_executable(cmeta_structured_conformance_gen EXCLUDE_FROM_ALL
  cmeta_structured_conformance_gen.c)

target_compile_features(cmeta_structured_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_structured_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_structured_conformance_gen PROPERTIES FOLDER "formal")

add_executable(cmeta_structured_policy_conformance_gen EXCLUDE_FROM_ALL
  cmeta_structured_policy_conformance_gen.c)

target_compile_features(cmeta_structured_policy_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_structured_policy_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_structured_policy_conformance_gen PROPERTIES FOLDER "formal")

add_executable(cmeta_optimizer_conformance_gen EXCLUDE_FROM_ALL
  cmeta_optimizer_conformance_gen.c)

target_compile_features(cmeta_optimizer_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_optimizer_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_optimizer_conformance_gen PROPERTIES FOLDER "formal")

add_executable(cmeta_optimizer_gating_conformance_gen EXCLUDE_FROM_ALL
  cmeta_optimizer_gating_conformance_gen.c)

target_compile_features(cmeta_optimizer_gating_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_optimizer_gating_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_optimizer_gating_conformance_gen PROPERTIES FOLDER "formal")

add_executable(cmeta_optimizer_topology_conformance_gen EXCLUDE_FROM_ALL
  cmeta_optimizer_topology_conformance_gen.c)

target_compile_features(cmeta_optimizer_topology_conformance_gen PRIVATE c_std_11)
target_link_libraries(cmeta_optimizer_topology_conformance_gen PRIVATE TurboUtils::CFlow)
set_target_properties(cmeta_optimizer_topology_conformance_gen PROPERTIES FOLDER "formal")
