#include <stdio.h>

#include <cflow/operators.h>
#include <cflow/operator_policy.h>

#define CMETA_FORMAL_STR_I(x) #x
#define CMETA_FORMAL_STR(x) CMETA_FORMAL_STR_I(x)

#define EMIT_TYPE_TOKEN(row, ignored) \
    printf("  \"%s\" ::\n", CMETA_FORMAL_STR(CMETA_TYPE_TOKEN(row)));

#define EMIT_POLICY_ID(id, ignored) \
    printf("  \"%s\" ::\n", CMETA_FORMAL_STR(id));

#define EMIT_SCHEMA(E, method_, margc, fnarg, subgrapharg, farity, p0, p1, p2, ret_, out_, card_, subgraphrule_, semantic_, intrinsic_effects_) \
    printf("  { enumName := \"%s\", method := \"%s\", methodArgc := %u, fnArg := %d, subgraphArg := %d, fnArity := %u, " \
           "p0 := \"%s\", p1 := \"%s\", p2 := \"%s\", ret := \"%s\", output := \"%s\", " \
           "cardinality := \"%s\", subgraphRule := \"%s\", semantic := \"%s\", effects := \"%s\" } ::\n", \
           #E, #method_, (unsigned)(margc), (int)(fnarg), (int)(subgrapharg), (unsigned)(farity), \
           #p0, #p1, #p2, #ret_, #out_, #card_, #subgraphrule_, #semantic_, #intrinsic_effects_);

static void emit_policy(const char *name, int which) {
    printf("def %s : List String :=\n", name);
    switch (which) {
        case 0:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_FILTER_SIGNATURE_LIST)
            break;
        case 1:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_MAP_SIGNATURE_LIST)
            break;
        case 2:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_TRANSFORM_SIGNATURE_LIST)
            break;
        case 3:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_FLAT_MAP_SIGNATURE_LIST)
            break;
        case 4:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_REDUCE_SIGNATURE_LIST)
            break;
        case 5:
            CMETA_PP_FOR_EACH_A(EMIT_POLICY_ID, ~, CFLOW_BUILTIN_ZIP_SIGNATURE_LIST)
            break;
        default:
            break;
    }
    printf("  []\n\n");
}

int main(void) {
    puts("module");
    puts("");
    puts("import Std");
    puts("");
    puts("/-! GENERATED by formal/cmeta_conformance_gen.c from CMeta/CFlow headers. -/");
    puts("");
    puts("namespace CMeta.CGenerated");
    puts("");
    puts("structure OperatorSchemaRow where");
    puts("  enumName : String");
    puts("  method : String");
    puts("  methodArgc : Nat");
    puts("  fnArg : Int");
    puts("  subgraphArg : Int");
    puts("  fnArity : Nat");
    puts("  p0 : String");
    puts("  p1 : String");
    puts("  p2 : String");
    puts("  ret : String");
    puts("  output : String");
    puts("  cardinality : String");
    puts("  subgraphRule : String");
    puts("  semantic : String");
    puts("  effects : String");
    puts("  deriving Repr, DecidableEq");
    puts("");

    puts("def builtinTypeTokens : List String :=");
    CMETA_PP_FOR_EACH_A(EMIT_TYPE_TOKEN, ~, CMETA_BUILTIN_TYPE_LIST)
    puts("  []");
    puts("");

    emit_policy("filterPolicyIds", 0);
    emit_policy("mapPolicyIds", 1);
    emit_policy("transformPolicyIds", 2);
    emit_policy("flatMapPolicyIds", 3);
    emit_policy("reducePolicyIds", 4);
    emit_policy("zipPolicyIds", 5);

    puts("def operatorSchemas : List OperatorSchemaRow :=");
    Replay(CFlowOperators, EMIT_SCHEMA)
    puts("  []");
    puts("");
    puts("end CMeta.CGenerated");
    return 0;
}

#undef EMIT_SCHEMA
#undef EMIT_POLICY_ID
#undef EMIT_TYPE_TOKEN
#undef CMETA_FORMAL_STR
#undef CMETA_FORMAL_STR_I
