#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <cflow/adapters.h>
#include <cflow/graph.h>
#include <cflow/lower.h>
#include <cflow/meta.h>
#include <cflow/opt.h>

typed_raw(map, CMETA_EFFECT_PURE,
          CMETA_PROP_DETERMINISTIC | CMETA_PROP_TOTAL |
              CMETA_PROP_IDEMPOTENT | CMETA_PROP_NO_ALIAS,
          int, conf_opt_idempotent_identity, (int x)) {
    return x;
}

typed_raw(map, CMETA_EFFECT_PURE,
          CMETA_PROP_DETERMINISTIC | CMETA_PROP_TOTAL | CMETA_PROP_NO_ALIAS,
          int, conf_opt_plain_identity, (int x)) {
    return x;
}

static const char *type_token(const cmeta_type_desc *type) {
    if (cmeta_type_equal(type, &cmeta_type_bool)) return "B";
    if (cmeta_type_equal(type, &cmeta_type_int)) return "I";
    if (cmeta_type_equal(type, &cmeta_type_long)) return "L";
    if (cmeta_type_equal(type, &cmeta_type_float)) return "F";
    if (cmeta_type_equal(type, &cmeta_type_double)) return "D";
    return NULL;
}

static int emit_int_values(const void *data, size_t count) {
    const int *values = (const int *)data;
    size_t i;
    if (count && !data) return 0;
    printf("[");
    for (i = 0; i < count; ++i) {
        if (i) printf(", ");
        printf("%d", values[i]);
    }
    printf("]");
    return 1;
}

static int build_duplicate_maps(cflow_graph *graph, cmeta_callable fn) {
    cflow_graph_init(graph, &cmeta_type_int);
    if (graph->root == CMETA_INVALID_ID) return 0;
    return cflow_graph_map(graph, fn) && cflow_graph_map(graph, fn);
}

static int emit_optimizer_witness(const char *name, cmeta_callable fn) {
    static const int inputs[] = { -2, 0, 3 };
    cflow_graph surface = {0};
    cflow_graph normalized = {0};
    cflow_graph optimized = {0};
    cflow_result before = {0};
    cflow_result after = {0};
    cflow_opt_stats stats = {0};
    const cflow_subgraph *root;
    const cflow_node *map;
    const char *input_type;
    const char *output_type;
    int ok = 0;

    normalized.root = CMETA_INVALID_ID;
    optimized.root = CMETA_INVALID_ID;

    if (!build_duplicate_maps(&surface, fn)) goto done;
    if (!cflow_graph_normalize(&normalized, &surface)) goto done;
    if (!cflow_graph_optimize(&optimized, &normalized,
                              (cflow_opt_options){ CMETA_OPT_DEFAULT }, &stats))
        goto done;

    root = cflow_graph_subgraph(&optimized, optimized.root);
    map = root ? cflow_subgraph_node(root, root->tail) : NULL;
    if (!root || !map || map->op != CFLOW_OP_MAP ||
        !map->fn_chain || map->fn_chain_count == 0u)
        goto done;

    input_type = type_token(root->input_type);
    output_type = type_token(root->output_type);
    if (!input_type || !output_type) goto done;

    if (!cflow_eval_array(&normalized, inputs, 3u, &before) ||
        !cflow_eval_array(&optimized, inputs, 3u, &after))
        goto done;
    if (!cmeta_type_equal(before.type, &cmeta_type_int) ||
        !cmeta_type_equal(after.type, &cmeta_type_int))
        goto done;

    printf("  { name := \"%s\", inputType := \"%s\", outputType := \"%s\",\n",
           name, input_type, output_type);
    printf("    nodesBefore := %zu, nodesAfter := %zu, mapNodesFused := %zu,\n",
           stats.nodes_before, stats.nodes_after, stats.map_nodes_fused);
    printf("    fnChainCount := %zu, idempotentEliminated := %zu, propertyBlocked := %zu,\n",
           map->fn_chain_count, stats.idempotent_maps_eliminated,
           stats.property_blocked_idempotent_eliminations);
    printf("    input := ");
    if (!emit_int_values(inputs, 3u)) goto done;
    printf(", before := ");
    if (!emit_int_values(before.data, before.count)) goto done;
    printf(", after := ");
    if (!emit_int_values(after.data, after.count)) goto done;
    printf(" } ::\n");
    ok = 1;

done:
    cflow_result_destroy(&after);
    cflow_result_destroy(&before);
    cflow_graph_destroy(&optimized);
    cflow_graph_destroy(&normalized);
    cflow_graph_destroy(&surface);
    return ok;
}

int main(void) {
    puts("module");
    puts("import Std");
    puts("");
    puts("/-! GENERATED by formal/cmeta_optimizer_conformance_gen.c using the real CFlow optimizer/runtime. -/");
    puts("");
    puts("namespace CMeta.COptimizerGenerated");
    puts("");
    puts("structure OptimizerWitness where");
    puts("  name : String");
    puts("  inputType : String");
    puts("  outputType : String");
    puts("  nodesBefore : Nat");
    puts("  nodesAfter : Nat");
    puts("  mapNodesFused : Nat");
    puts("  fnChainCount : Nat");
    puts("  idempotentEliminated : Nat");
    puts("  propertyBlocked : Nat");
    puts("  input : List Int");
    puts("  before : List Int");
    puts("  after : List Int");
    puts("  deriving Repr, DecidableEq");
    puts("");
    puts("def optimizerWitnesses : List OptimizerWitness :=");
    if (!emit_optimizer_witness("duplicate_idempotent_identity_i",
                                conf_opt_idempotent_identity.fn) ||
        !emit_optimizer_witness("duplicate_plain_identity_i",
                                conf_opt_plain_identity.fn))
        return EXIT_FAILURE;
    puts("  []");
    puts("");
    puts("end CMeta.COptimizerGenerated");
    return EXIT_SUCCESS;
}
