#ifndef TINYMOCK_CMETA_H
#define TINYMOCK_CMETA_H

/*
 * CMeta interface bridge for TinyMock.
 *
 * This header deliberately replays an existing CMETA_INTERFACE method schema.
 * It does not define a second interface/function reflection model and it does
 * not make TinyTest itself depend on CMeta.
 *
 * TinyMock interface mocking accepts fully reflected F/FR/FV/FD rows only.
 * They consume the canonical CMeta FunctionDesc/FunctionAbi generated by
 * CMETA_INTERFACE and share the same typed history, output-action, capture and
 * typed-return runtime as reflected free-function mocks. Legacy R/V/D interface
 * rows remain a CMeta source-compatibility facility, but are not a TinyMock
 * semantic path.
 */

#include "tinymock_support.h"
#include "tinymock_history.h"
#include "tinymock_actions.h"
#include "tinymock_return.h"
#include <cmeta/interface.h>
#include <cmeta/data.h>

#ifdef __cplusplus
#error "tinymock_cmeta.h is the strict-C11 CMeta interface mock bridge"
#endif

#define TINYMOCk_INTERFACE_TYPE(I) TINYMOCk_CAT(tinymock_, I)
#define TINYMOCk_INTERFACE_METHOD_BASE(I, N) \
  TINYMOCk_CAT(TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _), N)
#define TINYMOCk_INTERFACE_CALLBACK(I, N) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_METHOD_BASE(I, N), _callback)
#define TINYMOCk_INTERFACE_VTABLE(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _vtable)
#define TINYMOCk_INTERFACE_INIT(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _init)
#define TINYMOCk_INTERFACE_AS(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _as_interface)
#define TINYMOCk_INTERFACE_DESTROY(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _destroy)

#define TINYMOCk_INTERFACE_HISTORY_NAME(N) TINYMOCk_CAT(N, _history)
#define TINYMOCk_INTERFACE_ACTIONS_NAME(N) TINYMOCk_CAT(N, _actions)
#define TINYMOCk_INTERFACE_RETURN_NAME(N) TINYMOCk_CAT(N, _return)

#define TINYMOCk_INTERFACE_ANCHOR(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _interface_anchor_t)

#define TINYMOCk_INTERFACE_DATA_ACCESSOR(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_data)
#define TINYMOCk_INTERFACE_DATA_DESC(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_data_desc)
#define TINYMOCk_INTERFACE_TYPE_DESC(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_type_desc)
#define TINYMOCk_INTERFACE_DATA_SHAPE(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_data_shape)
#define TINYMOCk_INTERFACE_CONSTRUCT_OPS(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_construct_ops)
#define TINYMOCk_INTERFACE_INIT_ZERO(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_init_zero)
#define TINYMOCk_INTERFACE_RESTORE_ZERO(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_restore_zero)
#define TINYMOCk_INTERFACE_MOVE_VALUE(I) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_TYPE(I), _cmeta_move)

#define TINYMOCk_INTERFACE_FIELD_REFLECTED(I, K, R, N, ...) \
  tinymock_cmeta_history TINYMOCk_INTERFACE_HISTORY_NAME(N); \
  tinymock_cmeta_actions TINYMOCk_INTERFACE_ACTIONS_NAME(N); \
  tinymock_cmeta_return TINYMOCk_INTERFACE_RETURN_NAME(N);

#define TINYMOCk_INTERFACE_FIELD_F0 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_F1 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_F2 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_F3 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_F4 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FR0 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FR1 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FR2 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FR3 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FR4 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FV0 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FV1 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FV2 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FV3 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FV4 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_FD0 TINYMOCk_INTERFACE_FIELD_REFLECTED
#define TINYMOCk_INTERFACE_FIELD_ROW(I, K, R, N, ...) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_FIELD_, K)(I, K, R, N, __VA_ARGS__)

#define TINYMOCk_INTERFACE_PARAM_ABI_I(type,name,flags,descriptor,abi) abi
#define TINYMOCk_INTERFACE_PARAM_ABI(row) TINYMOCk_INTERFACE_PARAM_ABI_I row

#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_SCALAR(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_OBJECT_POINTER(value) \
  { (const void *)&(value), true, (const void *)(value) }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_AGGREGATE(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_FUNCTION_POINTER(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_ENUM(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_UNSPECIFIED(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_OPAQUE(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_CMETA_ABI_VOID(value) \
  { (const void *)&(value), false, NULL }
#define TINYMOCk_INTERFACE_VIEW_I(abi, value) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_VIEW_, abi)(value)
#define TINYMOCk_INTERFACE_ARG_VIEW(row) \
  TINYMOCk_INTERFACE_VIEW_I( \
      TINYMOCk_INTERFACE_PARAM_ABI(row), CMETA_IFACE_PARAM_NAME(row))
#define TINYMOCk_INTERFACE_TYPED_ROW(index, row, ignored) \
  CMETA_PP_CAT(CMETA_FUNCTION_COMMA_, index) \
  TINYMOCk_INTERFACE_ARG_VIEW(row)

#define TINYMOCk_INTERFACE_PARAM_ADMIT_I(type,name,flags,descriptor,abi) \
  _Static_assert( \
      (abi) == CMETA_ABI_SCALAR || \
      (abi) == CMETA_ABI_OBJECT_POINTER || \
      (abi) == CMETA_ABI_AGGREGATE || \
      (abi) == CMETA_ABI_FUNCTION_POINTER || \
      (abi) == CMETA_ABI_ENUM, \
      "TinyMock reflected interface parameter uses an unsupported ABI carrier")
#define TINYMOCk_INTERFACE_PARAM_ADMIT(row) \
  TINYMOCk_INTERFACE_PARAM_ADMIT_I row
#define TINYMOCk_INTERFACE_PARAM_ADMIT_ROW(row, ignored) \
  TINYMOCk_INTERFACE_PARAM_ADMIT(row);

#define TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(abi) \
  _Static_assert( \
      (abi) == CMETA_ABI_SCALAR || \
      (abi) == CMETA_ABI_OBJECT_POINTER || \
      (abi) == CMETA_ABI_AGGREGATE || \
      (abi) == CMETA_ABI_FUNCTION_POINTER || \
      (abi) == CMETA_ABI_ENUM, \
      "TinyMock reflected interface return uses an unsupported ABI carrier")
#define TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(abi) \
  _Static_assert((abi) == CMETA_ABI_VOID, \
      "TinyMock reflected void interface return must use CMETA_ABI_VOID")

#define TINYMOCk_INTERFACE_RECORD(I,N,argc,typed) \
  TINYMOCk_ASSERT( \
      tinymock_cmeta_history_record( \
          &mock->TINYMOCk_INTERFACE_HISTORY_NAME(N), I##_##N##_function(), \
          (argc), (typed)), \
      "tinymock cannot snapshot reflected interface arguments for %s.%s", \
      #I, #N)

#define TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,argc,typed) \
  TINYMOCk_ASSERT( \
      tinymock_cmeta_actions_apply( \
          &mock->TINYMOCk_INTERFACE_ACTIONS_NAME(N), I##_##N##_function(), \
          (argc), (typed)), \
      "tinymock cannot apply reflected interface output actions for %s.%s", \
      #I, #N)

#define TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R) \
  do { \
    R typed_result__; \
    bool ok__ = tinymock_cmeta_return_write( \
        &mock->TINYMOCk_INTERFACE_RETURN_NAME(N), \
        I##_##N##_function(), &typed_result__); \
    TINYMOCk_ASSERT(ok__, \
        "tinymock reflected interface return for %s.%s requires a typed return", \
        #I, #N); \
    if (ok__) return typed_result__; \
    return (R){0}; \
  } while (0)

#define TINYMOCk_INTERFACE_RETURN_CMETA_ABI_SCALAR(I,N,R) \
  TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R)
#define TINYMOCk_INTERFACE_RETURN_CMETA_ABI_OBJECT_POINTER(I,N,R) \
  TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R)
#define TINYMOCk_INTERFACE_RETURN_CMETA_ABI_AGGREGATE(I,N,R) \
  TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R)
#define TINYMOCk_INTERFACE_RETURN_CMETA_ABI_FUNCTION_POINTER(I,N,R) \
  TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R)
#define TINYMOCk_INTERFACE_RETURN_CMETA_ABI_ENUM(I,N,R) \
  TINYMOCk_INTERFACE_RETURN_TYPED_ONLY(I,N,R)
#define TINYMOCk_INTERFACE_RETURN_VALUE(abi,I,N,R) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_RETURN_, abi)(I,N,R)

#define TINYMOCk_INTERFACE_CALLBACK_F0(I,R,N,C,RD,RA) \
  TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(RA); \
  static R TINYMOCk_INTERFACE_CALLBACK(I, N)(void *opaque) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    TINYMOCk_INTERFACE_RECORD(I,N,0u,NULL); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,0u,NULL); \
    TINYMOCk_INTERFACE_RETURN_VALUE(RA,I,N,R); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_F1(I,R,N,C,RD,RA,P1) \
  TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); \
  static R TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { TINYMOCk_INTERFACE_ARG_VIEW(P1) }; \
    TINYMOCk_INTERFACE_RECORD(I,N,1u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,1u,typed__); \
    TINYMOCk_INTERFACE_RETURN_VALUE(RA,I,N,R); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_F2(I,R,N,C,RD,RA,P1,P2) \
  TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  static R TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,2u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,2u,typed__); \
    TINYMOCk_INTERFACE_RETURN_VALUE(RA,I,N,R); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_F3(I,R,N,C,RD,RA,P1,P2,P3) \
  TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P3); \
  static R TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2), \
      CMETA_IFACE_PARAM_DECL(P3)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2), \
      TINYMOCk_INTERFACE_ARG_VIEW(P3) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,3u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,3u,typed__); \
    TINYMOCk_INTERFACE_RETURN_VALUE(RA,I,N,R); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_F4(I,R,N,C,RD,RA,P1,P2,P3,P4) \
  TINYMOCk_INTERFACE_VALUE_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P3); TINYMOCk_INTERFACE_PARAM_ADMIT(P4); \
  static R TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2), \
      CMETA_IFACE_PARAM_DECL(P3), CMETA_IFACE_PARAM_DECL(P4)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2), \
      TINYMOCk_INTERFACE_ARG_VIEW(P3), TINYMOCk_INTERFACE_ARG_VIEW(P4) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,4u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,4u,typed__); \
    TINYMOCk_INTERFACE_RETURN_VALUE(RA,I,N,R); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FR0(I,R,N,C,RD,RA,RF) \
  TINYMOCk_INTERFACE_CALLBACK_F0(I,R,N,C,RD,RA)
#define TINYMOCk_INTERFACE_CALLBACK_FR1(I,R,N,C,RD,RA,RF,P1) \
  TINYMOCk_INTERFACE_CALLBACK_F1(I,R,N,C,RD,RA,P1)
#define TINYMOCk_INTERFACE_CALLBACK_FR2(I,R,N,C,RD,RA,RF,P1,P2) \
  TINYMOCk_INTERFACE_CALLBACK_F2(I,R,N,C,RD,RA,P1,P2)
#define TINYMOCk_INTERFACE_CALLBACK_FR3(I,R,N,C,RD,RA,RF,P1,P2,P3) \
  TINYMOCk_INTERFACE_CALLBACK_F3(I,R,N,C,RD,RA,P1,P2,P3)
#define TINYMOCk_INTERFACE_CALLBACK_FR4(I,R,N,C,RD,RA,RF,P1,P2,P3,P4) \
  TINYMOCk_INTERFACE_CALLBACK_F4(I,R,N,C,RD,RA,P1,P2,P3,P4)

#define TINYMOCk_INTERFACE_CALLBACK_FV0(I,R,N,C,RD,RA) \
  TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(RA); \
  static void TINYMOCk_INTERFACE_CALLBACK(I, N)(void *opaque) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    TINYMOCk_INTERFACE_RECORD(I,N,0u,NULL); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,0u,NULL); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FV1(I,R,N,C,RD,RA,P1) \
  TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); \
  static void TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { TINYMOCk_INTERFACE_ARG_VIEW(P1) }; \
    TINYMOCk_INTERFACE_RECORD(I,N,1u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,1u,typed__); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FV2(I,R,N,C,RD,RA,P1,P2) \
  TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  static void TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,2u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,2u,typed__); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FV3(I,R,N,C,RD,RA,P1,P2,P3) \
  TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P3); \
  static void TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2), \
      CMETA_IFACE_PARAM_DECL(P3)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2), \
      TINYMOCk_INTERFACE_ARG_VIEW(P3) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,3u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,3u,typed__); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FV4(I,R,N,C,RD,RA,P1,P2,P3,P4) \
  TINYMOCk_INTERFACE_VOID_RETURN_ADMIT(RA); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P1); TINYMOCk_INTERFACE_PARAM_ADMIT(P2); \
  TINYMOCk_INTERFACE_PARAM_ADMIT(P3); TINYMOCk_INTERFACE_PARAM_ADMIT(P4); \
  static void TINYMOCk_INTERFACE_CALLBACK(I, N)( \
      void *opaque, CMETA_IFACE_PARAM_DECL(P1), CMETA_IFACE_PARAM_DECL(P2), \
      CMETA_IFACE_PARAM_DECL(P3), CMETA_IFACE_PARAM_DECL(P4)) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = (TINYMOCk_INTERFACE_TYPE(I) *)opaque; \
    tinymock_cmeta_arg_view typed__[] = { \
      TINYMOCk_INTERFACE_ARG_VIEW(P1), TINYMOCk_INTERFACE_ARG_VIEW(P2), \
      TINYMOCk_INTERFACE_ARG_VIEW(P3), TINYMOCk_INTERFACE_ARG_VIEW(P4) \
    }; \
    TINYMOCk_INTERFACE_RECORD(I,N,4u,typed__); \
    TINYMOCk_INTERFACE_APPLY_ACTIONS(I,N,4u,typed__); \
  }

#define TINYMOCk_INTERFACE_CALLBACK_FD0(I,R,N,C,RD,RA) \
  TINYMOCk_INTERFACE_CALLBACK_FV0(I,R,N,C,RD,RA)

#define TINYMOCk_INTERFACE_CALLBACK_ROW(I, K, R, N, ...) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_CALLBACK_, K)(I, R, N, __VA_ARGS__)

#define TINYMOCk_INTERFACE_VTABLE_ROW(I, K, R, N, ...) \
  .N = TINYMOCk_INTERFACE_CALLBACK(I, N),

#define TINYMOCk_INTERFACE_INIT_REFLECTED(I,N) \
  TINYMOCk_ASSERT(cmeta_function_desc_valid(I##_##N##_function()), \
                  "tinymock reflected interface metadata is invalid: %s.%s", \
                  #I, #N); \
  TINYMOCk_ASSERT(cmeta_function_abi_desc_valid(I##_##N##_function_abi()), \
                  "tinymock reflected interface ABI metadata is invalid: %s.%s", \
                  #I, #N); \
  tinymock_cmeta_history_init( \
      &mock->TINYMOCk_INTERFACE_HISTORY_NAME(N), I##_##N##_function()); \
  tinymock_cmeta_actions_init( \
      &mock->TINYMOCk_INTERFACE_ACTIONS_NAME(N), I##_##N##_function()); \
  tinymock_cmeta_return_init( \
      &mock->TINYMOCk_INTERFACE_RETURN_NAME(N), I##_##N##_function());

#define TINYMOCk_INTERFACE_INIT_F0(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_F1(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_F2(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_F3(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_F4(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FR0(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FR1(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FR2(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FR3(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FR4(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FV0(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FV1(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FV2(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FV3(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FV4(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_FD0(I,R,N,...) TINYMOCk_INTERFACE_INIT_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_INIT_ROW(I, K, R, N, ...) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_INIT_, K)(I,R,N,__VA_ARGS__)

#define TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N) \
  tinymock_cmeta_history_destroy(&mock->TINYMOCk_INTERFACE_HISTORY_NAME(N)); \
  tinymock_cmeta_actions_destroy(&mock->TINYMOCk_INTERFACE_ACTIONS_NAME(N)); \
  tinymock_cmeta_return_destroy(&mock->TINYMOCk_INTERFACE_RETURN_NAME(N));

#define TINYMOCk_INTERFACE_DESTROY_F0(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_F1(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_F2(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_F3(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_F4(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FR0(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FR1(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FR2(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FR3(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FR4(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FV0(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FV1(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FV2(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FV3(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FV4(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_FD0(I,R,N,...) TINYMOCk_INTERFACE_DESTROY_REFLECTED(I,N)
#define TINYMOCk_INTERFACE_DESTROY_ROW(I,K,R,N,...) \
  TINYMOCk_CAT(TINYMOCk_INTERFACE_DESTROY_, K)(I,R,N,__VA_ARGS__)

#define TINYMOCk_INTERFACE_WITH_CAPS(I, METHODS, CAPS) \
  typedef struct TINYMOCk_INTERFACE_TYPE(I) { \
    METHODS(TINYMOCk_INTERFACE_FIELD_ROW, I) \
  } TINYMOCk_INTERFACE_TYPE(I); \
  METHODS(TINYMOCk_INTERFACE_CALLBACK_ROW, I) \
  static const I##_vtable TINYMOCk_INTERFACE_VTABLE(I) = { \
    .implementation = "tinymock:" #I, \
    .capabilities = (uint64_t)(CAPS), \
    METHODS(TINYMOCk_INTERFACE_VTABLE_ROW, I) \
  }; \
  static inline void TINYMOCk_INTERFACE_INIT(I)(TINYMOCk_INTERFACE_TYPE(I) *mock) { \
    if (!mock) return; \
    *mock = (TINYMOCk_INTERFACE_TYPE(I)){0}; \
    METHODS(TINYMOCk_INTERFACE_INIT_ROW, I) \
  } \
  static inline void TINYMOCk_INTERFACE_DESTROY(I)(TINYMOCk_INTERFACE_TYPE(I) *mock) { \
    if (!mock) return; \
    METHODS(TINYMOCk_INTERFACE_DESTROY_ROW, I) \
    *mock = (TINYMOCk_INTERFACE_TYPE(I)){0}; \
  } \
  static inline I TINYMOCk_INTERFACE_AS(I)(TINYMOCk_INTERFACE_TYPE(I) *mock) { \
    return I##_bind(mock, &TINYMOCk_INTERFACE_VTABLE(I)); \
  } \
  static cmeta_status TINYMOCk_INTERFACE_INIT_ZERO(I)(void *object) { \
    TINYMOCk_INTERFACE_TYPE(I) *mock = \
        (TINYMOCk_INTERFACE_TYPE(I) *)object; \
    if (!mock) return CMETA_INVALID_ARGUMENT; \
    *mock = (TINYMOCk_INTERFACE_TYPE(I)){0}; \
    return CMETA_OK; \
  } \
  static void TINYMOCk_INTERFACE_RESTORE_ZERO(I)(void *object) { \
    TINYMOCk_INTERFACE_DESTROY(I)((TINYMOCk_INTERFACE_TYPE(I) *)object); \
  } \
  static void TINYMOCk_INTERFACE_MOVE_VALUE(I)(void *destination, void *source) { \
    TINYMOCk_INTERFACE_TYPE(I) *dst = \
        (TINYMOCk_INTERFACE_TYPE(I) *)destination; \
    TINYMOCk_INTERFACE_TYPE(I) *src = \
        (TINYMOCk_INTERFACE_TYPE(I) *)source; \
    if (!dst || !src || dst == src) return; \
    *dst = *src; \
    *src = (TINYMOCk_INTERFACE_TYPE(I)){0}; \
  } \
  static const cmeta_type_desc TINYMOCk_INTERFACE_TYPE_DESC(I) = { \
    .name = "tinymock_" #I, \
    .size = sizeof(TINYMOCk_INTERFACE_TYPE(I)), \
    .align = _Alignof(TINYMOCk_INTERFACE_TYPE(I)), \
    .kind = CMETA_T_OBJECT, \
    .pointee = NULL, .traits = NULL, .identity = NULL \
  }; \
  static const unsigned char TINYMOCk_INTERFACE_DATA_SHAPE(I) = 0u; \
  static const cmeta_data_construct_ops TINYMOCk_INTERFACE_CONSTRUCT_OPS(I) = { \
    .struct_size = sizeof(cmeta_data_construct_ops), \
    .abi_version = CMETA_DATA_CONSTRUCT_OPS_ABI_VERSION, \
    .storage_type = &TINYMOCk_INTERFACE_TYPE_DESC(I), \
    .init_zero = TINYMOCk_INTERFACE_INIT_ZERO(I), \
    .restore_zero = TINYMOCk_INTERFACE_RESTORE_ZERO(I), \
    .move = TINYMOCk_INTERFACE_MOVE_VALUE(I) \
  }; \
  static const cmeta_data_desc TINYMOCk_INTERFACE_DATA_DESC(I) = { \
    .struct_size = sizeof(cmeta_data_desc), \
    .abi_version = CMETA_DATA_DESC_ABI_VERSION, \
    .stable_id = "tinymock." #I ".data", \
    .display_name = "tinymock:" #I, \
    .kind = CMETA_DATA_CUSTOM, \
    .storage_type = &TINYMOCk_INTERFACE_TYPE_DESC(I), \
    .shape = &TINYMOCk_INTERFACE_DATA_SHAPE(I), \
    .construct_ops = &TINYMOCk_INTERFACE_CONSTRUCT_OPS(I) \
  }; \
  static inline const cmeta_data_desc *TINYMOCk_INTERFACE_DATA_ACCESSOR(I)(void) { \
    return &TINYMOCk_INTERFACE_DATA_DESC(I); \
  } \
  typedef int TINYMOCk_INTERFACE_ANCHOR(I)

#define TINYMOCk_INTERFACE(I, METHODS) \
  TINYMOCk_INTERFACE_WITH_CAPS(I, METHODS, 0u)

#define TINYMOCk_INTERFACE_METHOD_FUNCTION(I, method) I##_##method##_function()
#define TINYMOCk_INTERFACE_METHOD_ABI(I, method) I##_##method##_function_abi()
#define TINYMOCk_INTERFACE_METHOD_HISTORY(mock, method) \
  (&((mock)->TINYMOCk_INTERFACE_HISTORY_NAME(method)))
#define TINYMOCk_INTERFACE_CALL_COUNT(mock, method) \
  tinymock_cmeta_history_call_count( \
      TINYMOCk_INTERFACE_METHOD_HISTORY((mock), method))
#define TINYMOCk_INTERFACE_VERIFY_TIMES(mock, method, expected) \
  do { \
    size_t expected__ = (size_t)(expected); \
    size_t actual__ = TINYMOCk_INTERFACE_CALL_COUNT((mock), method); \
    TINYMOCk_ASSERT(actual__ == expected__, \
        "tinymock reflected interface %s: expected exactly %zu calls, got %zu", \
        #method, expected__, actual__); \
  } while (0)
#define TINYMOCk_INTERFACE_VERIFY_NEVER(mock, method) \
  TINYMOCk_INTERFACE_VERIFY_TIMES((mock), method, 0u)
#define TINYMOCk_INTERFACE_VERIFY_AT_LEAST(mock, method, minimum) \
  do { \
    size_t minimum__ = (size_t)(minimum); \
    size_t actual__ = TINYMOCk_INTERFACE_CALL_COUNT((mock), method); \
    TINYMOCk_ASSERT(actual__ >= minimum__, \
        "tinymock reflected interface %s: expected at least %zu calls, got %zu", \
        #method, minimum__, actual__); \
  } while (0)
#define TINYMOCk_INTERFACE_VERIFY_AT_MOST(mock, method, maximum) \
  do { \
    size_t maximum__ = (size_t)(maximum); \
    size_t actual__ = TINYMOCk_INTERFACE_CALL_COUNT((mock), method); \
    TINYMOCk_ASSERT(actual__ <= maximum__, \
        "tinymock reflected interface %s: expected at most %zu calls, got %zu", \
        #method, maximum__, actual__); \
  } while (0)
#define TINYMOCk_INTERFACE_METHOD_ACTIONS(mock, method) \
  (&((mock)->TINYMOCk_INTERFACE_ACTIONS_NAME(method)))
#define TINYMOCk_INTERFACE_METHOD_RETURN(mock, method) \
  (&((mock)->TINYMOCk_INTERFACE_RETURN_NAME(method)))

#define TINYMOCk_INTERFACE_SET_RETURN(mock, method, value_lvalue) \
  tinymock_cmeta_return_set( \
      TINYMOCk_INTERFACE_METHOD_RETURN((mock), method), \
      TINYMOCk_INTERFACE_METHOD_RETURN((mock), method)->function, \
      &(value_lvalue))
#define TINYMOCk_INTERFACE_CLEAR_RETURN(mock, method) \
  tinymock_cmeta_return_clear(TINYMOCk_INTERFACE_METHOD_RETURN((mock), method))
#define TINYMOCk_INTERFACE_ARG_EQUAL_TYPED( \
    mock, method, call_index, param_name, expected_lvalue) \
  tinymock_cmeta_history_arg_equal_typed_name( \
      TINYMOCk_INTERFACE_METHOD_HISTORY((mock), method), (call_index), \
      (param_name), &(expected_lvalue))
#define TINYMOCk_INTERFACE_CAPTURE( \
    mock, method, call_index, param_name, captor) \
  tinymock_cmeta_captor_capture_name( \
      (captor), TINYMOCk_INTERFACE_METHOD_HISTORY((mock), method), \
      (call_index), (param_name))
#define TINYMOCk_INTERFACE_SET_OUT(mock, method, param_name, value_lvalue) \
  tinymock_cmeta_actions_set_output_name( \
      TINYMOCk_INTERFACE_METHOD_ACTIONS((mock), method), \
      TINYMOCk_INTERFACE_METHOD_ACTIONS((mock), method)->function, \
      (param_name), &(value_lvalue))
#define TINYMOCk_INTERFACE_CLEAR_OUT(mock, method, param_name) \
  tinymock_cmeta_actions_clear_output_name( \
      TINYMOCk_INTERFACE_METHOD_ACTIONS((mock), method), (param_name))

#endif /* TINYMOCK_CMETA_H */
