cmake_minimum_required(VERSION 3.22)
project(cstl_allocator_installed LANGUAGES C CXX)
find_package(Salts CONFIG REQUIRED)
enable_testing()
add_executable(allocator_c ../cstl_vec_alloc_test.c)
add_executable(allocator_cpp ../cstl_vec_alloc_cpp_test.cpp)
foreach(target allocator_c allocator_cpp)
  target_link_libraries(${target} PRIVATE Salts::CSTL Salts::TinyTest)
  if(UNIX)
    target_link_libraries(${target} PRIVATE m)
  endif()
  add_test(NAME ${target} COMMAND ${target})
endforeach()
set_target_properties(allocator_c PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
set_target_properties(allocator_cpp PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
