import CMetaCFlowCalculus.CMeta.SignatureManifest

namespace CMetaCFlowCalculus.CMeta.SignatureHeader

private def rowName (token : String) : String :=
  "CMETA_ROW_" ++ token

private def renderRows : List String → String
  | [] => ""
  | [row] => "    " ++ row ++ "\n"
  | row :: rest => "    " ++ row ++ ", \\\n" ++ renderRows rest

private def renderListMacro (name : String) (rows : List String) : String :=
  "#define " ++ name ++ " \\\n" ++ renderRows rows

private def renderTypeRow (row : CTypeRow) : String :=
  "#define " ++ rowName row.token ++ " (" ++ row.token ++ ", " ++
    row.cType ++ ", " ++ row.descriptor ++ ", " ++ row.kind ++ ", " ++
    row.traits ++ ")"

private def renderUnary (relation : UnaryRelation) : String :=
  "(" ++ rowName relation.input ++ ", " ++ rowName relation.output ++ ")"

private def renderBinary (relation : BinaryRelation) : String :=
  "(" ++ rowName relation.left ++ ", " ++ rowName relation.right ++ ", " ++
    rowName relation.output ++ ")"

private def renderGenerator (relation : GeneratorRelation) : String :=
  "(" ++ rowName relation.input ++ ", " ++ rowName relation.output ++ ")"

private def renderValidated (manifest : SignatureManifest) : String :=
  let typeRows := String.intercalate "\n" (manifest.types.map renderTypeRow)
  let typeList := manifest.types.map (rowName ·.token)
  let unaryRows := manifest.unary.map renderUnary
  let binaryRows := manifest.binary.map renderBinary
  let generatorRows := manifest.generators.map renderGenerator
  "#ifndef CMETA_GENERATED_BUILTIN_SIGNATURE_MANIFEST_H\n" ++
  "#define CMETA_GENERATED_BUILTIN_SIGNATURE_MANIFEST_H\n\n" ++
  "/* Generated by cmeta-signature-gen. Do not edit by hand. */\n\n" ++
  typeRows ++ "\n\n" ++
  renderListMacro "CMETA_BUILTIN_TYPE_LIST" typeList ++ "\n" ++
  renderListMacro "CMETA_BUILTIN_UNARY_RELATION_LIST" unaryRows ++ "\n" ++
  renderListMacro "CMETA_BUILTIN_BINARY_RELATION_LIST" binaryRows ++ "\n" ++
  renderListMacro "CMETA_BUILTIN_GENERATOR_RELATION_LIST" generatorRows ++ "\n" ++
  "#define CMETA_BUILTIN_TYPE_COUNT " ++ toString manifest.types.length ++ "u\n" ++
  "#define CMETA_BUILTIN_UNARY_RELATION_COUNT " ++
    toString manifest.unary.length ++ "u\n" ++
  "#define CMETA_BUILTIN_BINARY_RELATION_COUNT " ++
    toString manifest.binary.length ++ "u\n" ++
  "#define CMETA_BUILTIN_GENERATOR_RELATION_COUNT " ++
    toString manifest.generators.length ++ "u\n\n" ++
  "#endif /* CMETA_GENERATED_BUILTIN_SIGNATURE_MANIFEST_H */\n"

def render (manifest : SignatureManifest) : Except ManifestError String :=
  match manifest.validate with
  | .error failure => .error failure
  | .ok () => .ok (renderValidated manifest)

end CMetaCFlowCalculus.CMeta.SignatureHeader
