add_library(s3_test_support STATIC s3_test_support.c)
target_compile_features(s3_test_support PUBLIC c_std_11)
target_include_directories(s3_test_support PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(s3_test_support PUBLIC Salts::CHTTP)
set_target_properties(s3_test_support PROPERTIES FOLDER "s3/tests")

add_executable(s3_signer_test s3_signer_test.c)
target_compile_features(s3_signer_test PRIVATE c_std_11)
target_link_libraries(s3_signer_test PRIVATE Salts::S3 Salts::TinyTest)
set_target_properties(s3_signer_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_signer_test COMMAND s3_signer_test)

add_executable(s3_header_cpp_test s3_header_cpp_test.cpp)
target_compile_features(s3_header_cpp_test PRIVATE cxx_std_17)
target_link_libraries(s3_header_cpp_test PRIVATE Salts::S3)
set_target_properties(s3_header_cpp_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_header_cpp_test COMMAND s3_header_cpp_test)

add_executable(s3_client_test s3_client_test.c)
target_compile_features(s3_client_test PRIVATE c_std_11)
target_link_libraries(s3_client_test PRIVATE Salts::S3 Salts::TinyTest s3_test_support)
set_target_properties(s3_client_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_client_test COMMAND s3_client_test)

add_executable(s3_operations_test s3_operations_test.c)
target_compile_features(s3_operations_test PRIVATE c_std_11)
target_link_libraries(s3_operations_test PRIVATE Salts::S3 Salts::TinyTest s3_test_support)
set_target_properties(s3_operations_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_operations_test COMMAND s3_operations_test)

add_executable(s3_file_test s3_file_test.c)
target_compile_features(s3_file_test PRIVATE c_std_11)
target_link_libraries(s3_file_test PRIVATE Salts::S3 Salts::TinyTest s3_test_support)
set_target_properties(s3_file_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_file_test COMMAND s3_file_test)

add_executable(s3_multipart_test s3_multipart_test.c)
target_compile_features(s3_multipart_test PRIVATE c_std_11)
target_link_libraries(s3_multipart_test PRIVATE Salts::S3 Salts::TinyTest s3_test_support)
set_target_properties(s3_multipart_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_multipart_test COMMAND s3_multipart_test)

add_executable(s3_bucket_config_test s3_bucket_config_test.c)
target_compile_features(s3_bucket_config_test PRIVATE c_std_11)
target_link_libraries(s3_bucket_config_test PRIVATE Salts::S3 Salts::TinyTest s3_test_support)
set_target_properties(s3_bucket_config_test PROPERTIES FOLDER "s3/tests")
add_test(NAME s3_bucket_config_test COMMAND s3_bucket_config_test)
