#ifndef CFLOW_OP_ROW_POLICY_H
#define CFLOW_OP_ROW_POLICY_H

#define CFLOW_FILTER_REL(in)          CMETA_U_ID(in, CMETA_ROW_B)
#define CFLOW_MAP_REL(in, out)        CMETA_U_ID(in, out)
#define CFLOW_TRANSFORM_REL(in, out)  CMETA_U_ID(in, out)
#define CFLOW_FLAT_MAP_REL(in, out)   CMETA_G_ID(in, out)
#define CFLOW_REDUCE_REL(t)           CMETA_B_ID(t, t, t)
#define CFLOW_ZIP_REL(a, b, out)      CMETA_B_ID(a, b, out)

#define CFLOW_BUILTIN_FILTER_SIGNATURE_LIST \
    CFLOW_FILTER_REL(CMETA_ROW_I)
#define CFLOW_BUILTIN_MAP_SIGNATURE_LIST \
    CFLOW_MAP_REL(CMETA_ROW_I, CMETA_ROW_I), \
    CFLOW_MAP_REL(CMETA_ROW_I, CMETA_ROW_L), \
    CFLOW_MAP_REL(CMETA_ROW_L, CMETA_ROW_D), \
    CFLOW_MAP_REL(CMETA_ROW_D, CMETA_ROW_I), \
    CFLOW_MAP_REL(CMETA_ROW_I, CMETA_ROW_D), \
    CFLOW_MAP_REL(CMETA_ROW_I, CMETA_ROW_F), \
    CFLOW_MAP_REL(CMETA_ROW_F, CMETA_ROW_D)
#define CFLOW_BUILTIN_TRANSFORM_SIGNATURE_LIST \
    CFLOW_TRANSFORM_REL(CMETA_ROW_I, CMETA_ROW_L)
#define CFLOW_BUILTIN_FLAT_MAP_SIGNATURE_LIST \
    CFLOW_FLAT_MAP_REL(CMETA_ROW_I, CMETA_ROW_L)
#define CFLOW_BUILTIN_REDUCE_SIGNATURE_LIST \
    CFLOW_REDUCE_REL(CMETA_ROW_L)
#define CFLOW_BUILTIN_ZIP_SIGNATURE_LIST \
    CFLOW_ZIP_REL(CMETA_ROW_L, CMETA_ROW_D, CMETA_ROW_D)

#ifndef CFLOW_USER_FILTER_SIGNATURE_LIST
#define CFLOW_USER_FILTER_SIGNATURE_LIST
#endif
#ifndef CFLOW_USER_MAP_SIGNATURE_LIST
#define CFLOW_USER_MAP_SIGNATURE_LIST
#endif
#ifndef CFLOW_USER_TRANSFORM_SIGNATURE_LIST
#define CFLOW_USER_TRANSFORM_SIGNATURE_LIST
#endif
#ifndef CFLOW_USER_FLAT_MAP_SIGNATURE_LIST
#define CFLOW_USER_FLAT_MAP_SIGNATURE_LIST
#endif
#ifndef CFLOW_USER_REDUCE_SIGNATURE_LIST
#define CFLOW_USER_REDUCE_SIGNATURE_LIST
#endif
#ifndef CFLOW_USER_ZIP_SIGNATURE_LIST
#define CFLOW_USER_ZIP_SIGNATURE_LIST
#endif

#define CFLOW_FILTER_SIGNATURE_LIST \
    CFLOW_BUILTIN_FILTER_SIGNATURE_LIST CFLOW_USER_FILTER_SIGNATURE_LIST
#define CFLOW_MAP_SIGNATURE_LIST \
    CFLOW_BUILTIN_MAP_SIGNATURE_LIST CFLOW_USER_MAP_SIGNATURE_LIST
#define CFLOW_TRANSFORM_SIGNATURE_LIST \
    CFLOW_BUILTIN_TRANSFORM_SIGNATURE_LIST CFLOW_USER_TRANSFORM_SIGNATURE_LIST
#define CFLOW_FLAT_MAP_SIGNATURE_LIST \
    CFLOW_BUILTIN_FLAT_MAP_SIGNATURE_LIST CFLOW_USER_FLAT_MAP_SIGNATURE_LIST
#define CFLOW_REDUCE_SIGNATURE_LIST \
    CFLOW_BUILTIN_REDUCE_SIGNATURE_LIST CFLOW_USER_REDUCE_SIGNATURE_LIST
#define CFLOW_ZIP_SIGNATURE_LIST \
    CFLOW_BUILTIN_ZIP_SIGNATURE_LIST CFLOW_USER_ZIP_SIGNATURE_LIST

#define CFLOW_filter_SIGNATURE_LIST    CFLOW_FILTER_SIGNATURE_LIST
#define CFLOW_map_SIGNATURE_LIST       CFLOW_MAP_SIGNATURE_LIST
#define CFLOW_transform_SIGNATURE_LIST CFLOW_TRANSFORM_SIGNATURE_LIST
#define CFLOW_flatMap_SIGNATURE_LIST   CFLOW_FLAT_MAP_SIGNATURE_LIST
#define CFLOW_reduce_SIGNATURE_LIST    CFLOW_REDUCE_SIGNATURE_LIST
#define CFLOW_zip_SIGNATURE_LIST       CFLOW_ZIP_SIGNATURE_LIST

#define CFLOW_OP_SIGNATURE_LIST_I(op) CFLOW_##op##_SIGNATURE_LIST
#define CFLOW_OP_SIGNATURE_LIST(op) CFLOW_OP_SIGNATURE_LIST_I(op)

#endif
