#ifndef TURBO_CONTAINER_STATUS_H
#define TURBO_CONTAINER_STATUS_H

typedef enum container_status {
  CONTAINER_OK = 0,
  CONTAINER_INVALID_ARGUMENT,
  CONTAINER_OUT_OF_MEMORY,
  CONTAINER_CAPACITY_EXCEEDED,
  CONTAINER_EMPTY,
  CONTAINER_NOT_FOUND,
  CONTAINER_TYPE_MISMATCH,
  CONTAINER_TRAIT_MISSING
} container_status;

#endif /* TURBO_CONTAINER_STATUS_H */
