"""Generate pinned Unicode 17 canonical normalization tables (no host UCD)."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/17.0.0"
HASHES = {
    "UnicodeData.txt": "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
    "DerivedNormalizationProps.txt": "71fd6a206a2c0cdd41feb6b7f656aa31091db45e9cedc926985d718397f9e488",
    "NormalizationTest.txt": "5019ffd530751a741900c849c0e010332f142a3612234639bd200b82138a87db",
}


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, digest in HASHES.items():
        if hashlib.sha256((DATA / name).read_bytes()).hexdigest() != digest:
            raise SystemExit(f"Unicode 17 input hash mismatch: {name}")
    decompositions, properties, exclusions = {}, {}, set()
    for line in (DATA / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
        f = line.split(";")
        cp = int(f[0], 16)
        prop = int(f[3]) | (256 if f[2].startswith("M") else 0)
        if prop:
            properties[cp] = prop
        if f[5] and not f[5].startswith("<"):
            decompositions[cp] = tuple(int(x, 16) for x in f[5].split())
    for line in (DATA / "DerivedNormalizationProps.txt").read_text(encoding="utf-8").splitlines():
        f = [x.strip() for x in line.split("#")[0].split(";")]
        if len(f) > 1 and f[1] == "Full_Composition_Exclusion":
            bounds = [int(x, 16) for x in f[0].split("..")]
            exclusions.update(range(bounds[0], bounds[-1] + 1))

    def expand(cp):
        return tuple(y for x in decompositions[cp] for y in expand(x)) if cp in decompositions else (cp,)

    lines = ["/* Generated by unicode/tools/generate_normalization_data.py; Unicode 17.0.0.",
             " * Data license: unicode/data/LICENSE.txt.",
             *(f" * {name} SHA-256: {digest}" for name, digest in HASHES.items()), " */"]
    values, entries = [], []
    for cp in sorted(decompositions):
        seq = expand(cp)
        assert len(seq) <= 4
        entries.append((cp, len(values), len(seq)))
        values.extend(seq)
    lines += ["static const uint32_t nfc_decomposition_values[] = {",
              *(f"  0x{x:x}u," for x in values), "};",
              "static const nfc_decomposition nfc_decompositions[] = {",
              *(f"  {{0x{cp:x}u, {offset}u, {size}u}}," for cp, offset, size in entries), "};"]
    compositions = sorted((seq[0], seq[1], cp) for cp, seq in decompositions.items()
                          if cp not in exclusions and len(seq) == 2)
    assert len({(a, b) for a, b, _ in compositions}) == len(compositions)
    lines += ["static const nfc_composition nfc_compositions[] = {",
              *(f"  {{0x{a:x}u, 0x{b:x}u, 0x{cp:x}u}}," for a, b, cp in compositions), "};"]
    ranges = []
    for cp, prop in sorted(properties.items()):
        if ranges and ranges[-1][1] + 1 == cp and ranges[-1][2] == prop:
            ranges[-1] = (ranges[-1][0], cp, prop)
        else:
            ranges.append((cp, cp, prop))
    lines += ["static const nfc_property_range nfc_properties[] = {",
              *(f"  {{0x{a:x}u, 0x{b:x}u, {v}u}}," for a, b, v in ranges), "};", ""]
    path = ROOT / "src/unicode_normalization_data.h"
    result = "\n".join(lines)
    if args.check:
        if path.read_text(encoding="ascii") != result:
            raise SystemExit("Stale normalization tables")
    else:
        path.write_text(result, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
