#ifndef CMETA_ENUM_H
#define CMETA_ENUM_H

#include <cmeta/pp.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

typedef struct cmeta_enum_item_desc {
    int64_t value;
    const char *symbol;
    const char *text;
} cmeta_enum_item_desc;

typedef struct cmeta_enum_desc {
    const char *name;
    const cmeta_enum_item_desc *items;
    size_t count;
} cmeta_enum_desc;

enum { CMETA_ENUM_DOMAIN_ABI_VERSION = 1u };

typedef enum cmeta_enum_signedness {
    CMETA_ENUM_SIGNED,
    CMETA_ENUM_UNSIGNED
} cmeta_enum_signedness;

typedef enum cmeta_enum_domain_kind {
    CMETA_ENUM_ORDINARY,
    CMETA_ENUM_FLAGS
} cmeta_enum_domain_kind;

typedef struct cmeta_enum_bits_item {
    uint64_t bits;
    const char *symbol;
    const char *text;
} cmeta_enum_bits_item;

/**
 * Immutable canonical enum domain, independent of native storage layout.
 * bits is 8, 16, 32 or 64. Values use only the low declared-width bits; negatives
 * use width-bit two's-complement (signed8 -1 is 255, not UINT64_MAX).
 * No signed conversion is required to transport or compare canonical bits.
 * Ordinary values must match an item exactly and declared_mask must be zero.
 * Flags accept any subset of declared_mask, including zero; declared_mask
 * must equal the bitwise OR of all items. Every item must fit the width and
 * have nonempty symbol/text. Aliases are permitted. Empty domains are valid.
 * Metadata and items remain provider-owned and live as long as their users.
 */
typedef struct cmeta_enum_domain {
    size_t struct_size;
    uint32_t abi_version;
    cmeta_enum_signedness signedness;
    uint8_t bits;
    cmeta_enum_domain_kind kind;
    const cmeta_enum_bits_item *items;
    size_t count;
    uint64_t declared_mask;
} cmeta_enum_domain;

#ifdef __cplusplus
#define CMETA_ENUM_TO_INT64(value) static_cast<int64_t>(value)
#define CMETA_ENUM_FROM_INT64(type, value) static_cast<type>(value)
#else
#define CMETA_ENUM_TO_INT64(value) ((int64_t)(value))
#define CMETA_ENUM_FROM_INT64(type, value) ((type)(value))
#endif

/* Generic enum reflection. Descriptors generated by Enum() have internal
 * linkage, so callers must compare descriptor contents rather than descriptor
 * addresses across translation units. */
CMETA_INLINE const cmeta_enum_item_desc *
cmeta_enum_item_by_value(const cmeta_enum_desc *desc, int64_t value) {
    size_t i;
    if (!desc) return NULL;
    for (i = 0; i < desc->count; ++i)
        if (desc->items[i].value == value) return &desc->items[i];
    return NULL;
}

CMETA_INLINE const char *cmeta_enum_to_string(const cmeta_enum_desc *desc,
                                                int64_t value) {
    const cmeta_enum_item_desc *item = cmeta_enum_item_by_value(desc, value);
    return item ? item->text : NULL;
}

CMETA_INLINE const char *cmeta_enum_to_symbol(const cmeta_enum_desc *desc,
                                                int64_t value) {
    const cmeta_enum_item_desc *item = cmeta_enum_item_by_value(desc, value);
    return item ? item->symbol : NULL;
}

CMETA_INLINE bool cmeta_enum_from_string(const cmeta_enum_desc *desc,
                                           const char *s,
                                           int64_t *out) {
    size_t i;
    if (!desc || !s || !out) return false;
    for (i = 0; i < desc->count; ++i) {
        const cmeta_enum_item_desc *item = &desc->items[i];
        if (strcmp(s, item->text) == 0 || strcmp(s, item->symbol) == 0) {
            *out = item->value;
            return true;
        }
    }
    return false;
}

/* Enum rows are parenthesized tuples. Two forms are accepted:
 *
 *   (SYMBOL, "text")          // normal C auto-increment value
 *   (SYMBOL, 404, "text")     // explicit stable value
 *
 * No Item wrapper is required.
 */

#define CMETA_ENUM_ITEM_DECL(...) \
    CMETA_PP_CAT(CMETA_ENUM_ITEM_DECL_, CMETA_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
#define CMETA_ENUM_ITEM_DECL_2(symbol, text) symbol,
#define CMETA_ENUM_ITEM_DECL_3(symbol, value, text) symbol = (value),

#define CMETA_ENUM_ITEM_DESC(...) \
    CMETA_PP_CAT(CMETA_ENUM_ITEM_DESC_, CMETA_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
#define CMETA_ENUM_ITEM_DESC_2(symbol, text) \
    { CMETA_ENUM_TO_INT64(symbol), #symbol, (text) },
#define CMETA_ENUM_ITEM_DESC_3(symbol, value, text) \
    { CMETA_ENUM_TO_INT64(symbol), #symbol, (text) },

/* Single-declaration enum schema.
 *
 *   Enum(Color,
 *       (COLOR_RED,   "red"),
 *       (COLOR_GREEN, "green"),
 *       (COLOR_BLUE,  "blue")
 *   );
 *
 * The declaration generates the enum, immutable reflection metadata and typed
 * helpers. No X-list #define and no implementation replay are required. */
#define CMETA_ENUM(type, ...) \
    typedef enum type { \
        Schema(CMETA_ENUM_ITEM_DECL, __VA_ARGS__) \
    } type; \
    CMETA_LOCAL const cmeta_enum_item_desc type##__enum_items[] = { \
        Schema(CMETA_ENUM_ITEM_DESC, __VA_ARGS__) \
    }; \
    CMETA_LOCAL const cmeta_enum_desc type##__enum_meta = { \
        #type, type##__enum_items, \
        sizeof(type##__enum_items) / sizeof(type##__enum_items[0]) \
    }; \
    CMETA_INLINE const char *type##_to_string(type value) { \
        return cmeta_enum_to_string(&type##__enum_meta, \
                                    CMETA_ENUM_TO_INT64(value)); \
    } \
    CMETA_INLINE const char *type##_to_symbol(type value) { \
        return cmeta_enum_to_symbol(&type##__enum_meta, \
                                    CMETA_ENUM_TO_INT64(value)); \
    } \
    CMETA_INLINE bool type##_from_string(const char *s, type *out) { \
        int64_t raw; \
        if (!out || !cmeta_enum_from_string(&type##__enum_meta, s, &raw)) return false; \
        *out = CMETA_ENUM_FROM_INT64(type, raw); \
        return true; \
    } \
    CMETA_INLINE const cmeta_enum_desc *type##_meta(void) { \
        return &type##__enum_meta; \
    } \
    typedef char type##__enum_declaration_complete[1]

#ifndef Enum
#define Enum(type, ...) CMETA_ENUM(type, __VA_ARGS__)
#endif

#define EnumMeta(type) (&type##__enum_meta)
#define EnumString(type, value) \
    cmeta_enum_to_string(EnumMeta(type), CMETA_ENUM_TO_INT64(value))
#define EnumSymbol(type, value) \
    cmeta_enum_to_symbol(EnumMeta(type), CMETA_ENUM_TO_INT64(value))
#define EnumParse(type, text, out) type##_from_string((text), (out))

#endif
