#ifndef CMETA_ENUM_H
#define CMETA_ENUM_H

#include <cmeta/pp.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

typedef struct cmeta_enum_item_desc {
    int64_t value;
    const char *symbol;
    const char *text;
} cmeta_enum_item_desc;

typedef struct cmeta_enum_desc {
    const char *name;
    const cmeta_enum_item_desc *items;
    size_t count;
} cmeta_enum_desc;

/* Generic enum reflection. Descriptors generated by Enum() have internal
 * linkage, so callers must compare descriptor contents rather than descriptor
 * addresses across translation units. */
static inline const cmeta_enum_item_desc *
cmeta_enum_item_by_value(const cmeta_enum_desc *desc, int64_t value) {
    size_t i;
    if (!desc) return NULL;
    for (i = 0; i < desc->count; ++i)
        if (desc->items[i].value == value) return &desc->items[i];
    return NULL;
}

static inline const char *cmeta_enum_to_string(const cmeta_enum_desc *desc,
                                                int64_t value) {
    const cmeta_enum_item_desc *item = cmeta_enum_item_by_value(desc, value);
    return item ? item->text : NULL;
}

static inline const char *cmeta_enum_to_symbol(const cmeta_enum_desc *desc,
                                                int64_t value) {
    const cmeta_enum_item_desc *item = cmeta_enum_item_by_value(desc, value);
    return item ? item->symbol : NULL;
}

static inline bool cmeta_enum_from_string(const cmeta_enum_desc *desc,
                                           const char *s,
                                           int64_t *out) {
    size_t i;
    if (!desc || !s || !out) return false;
    for (i = 0; i < desc->count; ++i) {
        const cmeta_enum_item_desc *item = &desc->items[i];
        if (strcmp(s, item->text) == 0 || strcmp(s, item->symbol) == 0) {
            *out = item->value;
            return true;
        }
    }
    return false;
}

/* Enum rows are parenthesized tuples. Two forms are accepted:
 *
 *   (SYMBOL, "text")          // normal C auto-increment value
 *   (SYMBOL, 404, "text")     // explicit stable value
 *
 * No Item wrapper is required.
 */

#define CMETA_ENUM_ITEM_DECL(...) \
    CMETA_PP_CAT(CMETA_ENUM_ITEM_DECL_, CMETA_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
#define CMETA_ENUM_ITEM_DECL_2(symbol, text) symbol,
#define CMETA_ENUM_ITEM_DECL_3(symbol, value, text) symbol = (value),

#define CMETA_ENUM_ITEM_DESC(...) \
    CMETA_PP_CAT(CMETA_ENUM_ITEM_DESC_, CMETA_PP_NARG(__VA_ARGS__))(__VA_ARGS__)
#define CMETA_ENUM_ITEM_DESC_2(symbol, text) \
    { (int64_t)(symbol), #symbol, (text) },
#define CMETA_ENUM_ITEM_DESC_3(symbol, value, text) \
    { (int64_t)(symbol), #symbol, (text) },

/* Single-declaration enum schema.
 *
 *   Enum(Color,
 *       (COLOR_RED,   "red"),
 *       (COLOR_GREEN, "green"),
 *       (COLOR_BLUE,  "blue")
 *   );
 *
 * The declaration generates the enum, immutable reflection metadata and typed
 * helpers. No X-list #define and no implementation replay are required. */
#define CMETA_ENUM(type, ...) \
    typedef enum type { \
        Schema(CMETA_ENUM_ITEM_DECL, __VA_ARGS__) \
    } type; \
    static const cmeta_enum_item_desc type##__enum_items[] = { \
        Schema(CMETA_ENUM_ITEM_DESC, __VA_ARGS__) \
    }; \
    static const cmeta_enum_desc type##__enum_meta = { \
        #type, type##__enum_items, \
        sizeof(type##__enum_items) / sizeof(type##__enum_items[0]) \
    }; \
    static inline const char *type##_to_string(type value) { \
        return cmeta_enum_to_string(&type##__enum_meta, (int64_t)value); \
    } \
    static inline const char *type##_to_symbol(type value) { \
        return cmeta_enum_to_symbol(&type##__enum_meta, (int64_t)value); \
    } \
    static inline bool type##_from_string(const char *s, type *out) { \
        int64_t raw; \
        if (!out || !cmeta_enum_from_string(&type##__enum_meta, s, &raw)) return false; \
        *out = (type)raw; \
        return true; \
    } \
    static inline const cmeta_enum_desc *type##_meta(void) { \
        return &type##__enum_meta; \
    } \
    typedef char type##__enum_declaration_complete[1]

#ifndef Enum
#define Enum(type, ...) CMETA_ENUM(type, __VA_ARGS__)
#endif

#define EnumMeta(type) (&type##__enum_meta)
#define EnumString(type, value) cmeta_enum_to_string(EnumMeta(type), (int64_t)(value))
#define EnumSymbol(type, value) cmeta_enum_to_symbol(EnumMeta(type), (int64_t)(value))
#define EnumParse(type, text, out) type##_from_string((text), (out))

#endif
