#ifndef CMETA_OBJECT_INTERFACE_H
#define CMETA_OBJECT_INTERFACE_H

#include <cmeta/interface.h>
#include <cmeta/object.h>

#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Provider-authorized borrowed Interface projection over one live ObjectRef.
 *
 * dispatch is an opaque pointer to the exact generated I_vtable selected by
 * the provider. Generic CMeta code never dereferences or invokes it. A typed
 * adapter generated by CMETA_OBJECT_INTERFACE_ADAPTER(I) performs the only
 * conversion to I_vtable and validates the resulting Interface handle.
 *
 * This carrier owns nothing. object/provider/module lifetime remains external.
 */
typedef struct cmeta_interface_projection {
    size_t size;
    const cmeta_interface_desc *interface;
    void *self;
    const void *dispatch;
} cmeta_interface_projection;

#ifdef __cplusplus
#define CMETA_INTERFACE_PROJECTION_INIT \
    { sizeof(cmeta_interface_projection), nullptr, nullptr, nullptr }
#else
#define CMETA_INTERFACE_PROJECTION_INIT \
    { .size = sizeof(cmeta_interface_projection), .interface = NULL, \
      .self = NULL, .dispatch = NULL }
#endif

typedef cmeta_status (*cmeta_object_interface_project_fn)(
    void *context,
    const cmeta_object_ref *object,
    const cmeta_interface_desc *expected,
    cmeta_interface_projection *out);

typedef struct cmeta_object_interface_provider {
    size_t size;
    void *context;
    cmeta_object_interface_project_fn project;
} cmeta_object_interface_provider;

CMETA_INLINE bool
cmeta_object_interface_provider_valid(
    const cmeta_object_interface_provider *provider) {
    return provider != NULL && provider->size >= sizeof(*provider) &&
           provider->project != NULL;
}

CMETA_INLINE bool
cmeta_interface_projection_valid_for(
    const cmeta_interface_projection *projection,
    const cmeta_interface_desc *expected) {
    return projection != NULL &&
           projection->size >= sizeof(*projection) &&
           cmeta_interface_desc_valid(projection->interface) &&
           cmeta_interface_desc_valid(expected) &&
           cmeta_interface_desc_equal(projection->interface, expected) &&
           projection->self != NULL &&
           projection->dispatch != NULL;
}

/*
 * Project one non-owning typed protocol capability from an ObjectRef.
 *
 * The provider, not descriptor equality, is the capability authority.
 * Interfaces containing CMETA_INTERFACE_METHOD_OWNS_SELF are rejected before
 * provider dispatch because a borrowed projection may not acquire independent
 * destroy authority over an ObjectRef that remains live.
 *
 * On every failure, out remains the canonical empty projection.
 */
CMETA_INLINE cmeta_status
cmeta_object_interface_project_borrowed(
    const cmeta_object_ref *object,
    const cmeta_object_interface_provider *provider,
    const cmeta_interface_desc *expected,
    cmeta_interface_projection *out) {
    cmeta_interface_projection candidate = CMETA_INTERFACE_PROJECTION_INIT;
    cmeta_status status;

    if (out == NULL)
        return CMETA_INVALID_ARGUMENT;
    *out = (cmeta_interface_projection)CMETA_INTERFACE_PROJECTION_INIT;

    if (!cmeta_object_ref_valid(object) ||
        !cmeta_object_interface_provider_valid(provider) ||
        !cmeta_interface_desc_valid(expected))
        return CMETA_INVALID_ARGUMENT;
    if (cmeta_interface_desc_has_owning_method(expected))
        return CMETA_TRAIT_MISSING;

    status = provider->project(
        provider->context, object, expected, &candidate);
    if (status != CMETA_OK)
        return status;
    if (!cmeta_interface_projection_valid_for(&candidate, expected))
        return CMETA_CALLBACK_ERROR;

    *out = candidate;
    return CMETA_OK;
}

#ifdef __cplusplus
}
#endif

/*
 * Opt-in exact typed bridge.
 *
 * The generic projection layer never interprets dispatch. This helper is
 * generated only for an explicitly named Interface and converts dispatch to
 * that Interface's exact I_vtable type before I_valid() checks the resulting
 * required-method surface.
 */
#define CMETA_OBJECT_INTERFACE_ADAPTER(I) \
    CMETA_INLINE cmeta_status I##_borrow_from_object( \
        const cmeta_object_ref *object, \
        const cmeta_object_interface_provider *provider, \
        I *out) { \
        cmeta_interface_projection projection = \
            CMETA_INTERFACE_PROJECTION_INIT; \
        cmeta_status status; \
        if (out == NULL) \
            return CMETA_INVALID_ARGUMENT; \
        *out = I##_bind(NULL, NULL); \
        status = cmeta_object_interface_project_borrowed( \
            object, provider, I##_interface(), &projection); \
        if (status != CMETA_OK) \
            return status; \
        *out = I##_bind( \
            projection.self, (const I##_vtable *)projection.dispatch); \
        if (!I##_valid(out)) { \
            *out = I##_bind(NULL, NULL); \
            return CMETA_CALLBACK_ERROR; \
        } \
        return CMETA_OK; \
    } \
    typedef int I##_object_interface_adapter_anchor_t

#endif /* CMETA_OBJECT_INTERFACE_H */
