#ifndef CMETA_POLICY_H
#define CMETA_POLICY_H

/* Concrete signature instantiation policy.
 * relation (default): O(E)
 * balanced: unary N^2 + return-right binary N^2 + generator N^2
 * full: unary N^2 + binary N^3 + generator N^2
 */
#if defined(CMETA_SIGNATURE_PROFILE_FULL)
#  define CMETA_SIGNATURE_PROFILE_NAME "full"
#  define CMETA_POLICY_UNARY(M)     CMETA_GEN_UNARY_ALL(M)
#  define CMETA_POLICY_BINARY(M)    CMETA_GEN_BINARY_ALL(M)
#  define CMETA_POLICY_GENERATOR(M) CMETA_GEN_GENERATOR_ALL(M)
#elif defined(CMETA_SIGNATURE_PROFILE_BALANCED)
#  define CMETA_SIGNATURE_PROFILE_NAME "balanced"
#  define CMETA_POLICY_UNARY(M)     CMETA_GEN_UNARY_ALL(M)
#  define CMETA_POLICY_BINARY(M)    CMETA_GEN_BINARY_RETURN_RIGHT(M)
#  define CMETA_POLICY_GENERATOR(M) CMETA_GEN_GENERATOR_ALL(M)
#else
#  define CMETA_SIGNATURE_PROFILE_NAME "relation"
#  define CMETA_POLICY_UNARY(M)     CMETA_GEN_UNARY_RELATIONS(M)
#  define CMETA_POLICY_BINARY(M)    CMETA_GEN_BINARY_RELATIONS(M)
#  define CMETA_POLICY_GENERATOR(M) CMETA_GEN_GENERATOR_RELATIONS(M)
#endif

#ifdef CMETA_CUSTOM_UNARY_POLICY
#  undef CMETA_POLICY_UNARY
#  define CMETA_POLICY_UNARY(M) CMETA_CUSTOM_UNARY_POLICY(M)
#endif
#ifdef CMETA_CUSTOM_BINARY_POLICY
#  undef CMETA_POLICY_BINARY
#  define CMETA_POLICY_BINARY(M) CMETA_CUSTOM_BINARY_POLICY(M)
#endif
#ifdef CMETA_CUSTOM_GENERATOR_POLICY
#  undef CMETA_POLICY_GENERATOR
#  define CMETA_POLICY_GENERATOR(M) CMETA_CUSTOM_GENERATOR_POLICY(M)
#endif

#endif
