#ifndef CMETA_TRACE_H
#define CMETA_TRACE_H

#include <cmeta/fastpath.h>
#include <salts/fastpath.h>
#include <cmeta/struct.h>

#ifndef __cplusplus
/* One definition per point, normally in the owning C module. Payload metadata
 * is generated by the existing Struct schema. Targets and gates permit MPMC
 * publication; replacement/disable does not drain in-flight callbacks. Backend
 * code must stay loaded until replaced and all old readers/callbacks finish;
 * payload is borrowed synchronously and must not escape or cross suspension. */
#define cmeta_tracepoint(name_, ...) \
    cmeta_struct(name_##_payload, __VA_ARGS__); \
    typedef void (*name_##_backend_type)(const name_##_payload *); \
    SALTS_FAST_KEY(name_##_key, false); \
    static _Atomic(name_##_backend_type) name_##_backend = NULL; \
    CMETA_INLINE cmeta_status name_##_bind(name_##_backend_type target_) { \
        if (target_ == NULL) return CMETA_INVALID_ARGUMENT; \
        atomic_store_explicit(&name_##_backend, target_, memory_order_release); \
        return CMETA_OK; \
    } \
    CMETA_INLINE cmeta_status name_##_enable(void) { \
        if (atomic_load_explicit(&name_##_backend, memory_order_acquire) == NULL) \
            return CMETA_INVALID_ARGUMENT; \
        return salts_fast_enable(&name_##_key) == SALTS_OK ? CMETA_OK : CMETA_INVALID_ARGUMENT; \
    } \
    typedef char name_##_trace_declaration_complete[1]

#define cmeta_trace_bind(name_, target_) \
    name_##_bind(_Generic((target_), name_##_backend_type: (target_)))
#define cmeta_trace_enable(name_) name_##_enable()
#define cmeta_trace_disable(name_) \
    (salts_fast_disable(&name_##_key) == SALTS_OK ? CMETA_OK : CMETA_INVALID_ARGUMENT)
#define cmeta_trace_emit(name_, ...) do { \
    if (salts_fast_branch(&name_##_key)) { \
        name_##_backend_type cmeta_trace_target_ = \
            atomic_load_explicit(&name_##_backend, memory_order_acquire); \
        if (cmeta_trace_target_ != NULL) { \
            const name_##_payload cmeta_trace_payload_ = {__VA_ARGS__}; \
            cmeta_trace_target_(&cmeta_trace_payload_); \
        } \
    } \
} while (0)
#endif

#endif
