#ifndef CMETA_TRACE_H
#define CMETA_TRACE_H

#include <cmeta/fastpath.h>
#include <cmeta/struct.h>

#ifdef __cplusplus
extern "C" {
#endif
/** Consume one armed fault permission in O(1). key must be live/non-NULL.
 * C++ borrows C-owned storage. Concurrent arms coalesce, not an event counter. */
bool cmeta_fault_consume(cmeta_static_key_state *key);
#ifdef __cplusplus
}
#else
CMETA_INLINE bool cmeta_fault_hit(cmeta_static_key_state *key) {
    return cmeta_static_branch(key) &&
        atomic_exchange_explicit(&key->enabled, false, memory_order_acq_rel);
}
#define cmeta_fault_point(name_) cmeta_static_key(name_, false)
#define cmeta_fault_arm(name_) cmeta_static_enable(&(name_))
#define cmeta_fault_disarm(name_) cmeta_static_disable(&(name_))

/* One definition per point, normally in the owning C module. Payload metadata
 * is generated by the existing Struct schema. Targets and gates permit MPMC
 * publication; replacement/disable does not drain in-flight callbacks. Backend
 * code must stay loaded until replaced and all old readers/callbacks finish;
 * payload is borrowed synchronously and must not escape or cross suspension. */
#define cmeta_tracepoint(name_, ...) \
    cmeta_struct(name_##_payload, __VA_ARGS__); \
    typedef void (*name_##_backend_type)(const name_##_payload *); \
    cmeta_static_key(name_##_key, false); \
    static _Atomic(name_##_backend_type) name_##_backend = NULL; \
    CMETA_INLINE cmeta_status name_##_bind(name_##_backend_type target_) { \
        if (target_ == NULL) return CMETA_INVALID_ARGUMENT; \
        atomic_store_explicit(&name_##_backend, target_, memory_order_release); \
        return CMETA_OK; \
    } \
    CMETA_INLINE cmeta_status name_##_enable(void) { \
        if (atomic_load_explicit(&name_##_backend, memory_order_acquire) == NULL) \
            return CMETA_INVALID_ARGUMENT; \
        return cmeta_static_enable(&name_##_key); \
    } \
    typedef char name_##_trace_declaration_complete[1]

#define cmeta_trace_bind(name_, target_) \
    name_##_bind(_Generic((target_), name_##_backend_type: (target_)))
#define cmeta_trace_enable(name_) name_##_enable()
#define cmeta_trace_disable(name_) cmeta_static_disable(&name_##_key)
#define cmeta_trace_emit(name_, ...) do { \
    if (cmeta_static_branch(&name_##_key)) { \
        name_##_backend_type cmeta_trace_target_ = \
            atomic_load_explicit(&name_##_backend, memory_order_acquire); \
        if (cmeta_trace_target_ != NULL) { \
            const name_##_payload cmeta_trace_payload_ = {__VA_ARGS__}; \
            cmeta_trace_target_(&cmeta_trace_payload_); \
        } \
    } \
} while (0)
#endif

#ifdef __cplusplus
#define cmeta_fault_hit(key_) cmeta_fault_consume(key_)
#endif

#endif
