# Resource metadata is Salts packaging policy, separate from generic target helpers.
set(SALTS_VERSION_COMPONENT_COUNT 4)
set(SALTS_VERSION_COMPONENT_MAX 65535)

foreach(SALTS_VERSION_TARGET IN ITEMS
    salts cnet cmeta_cmeta cmeta_cflow cmeta_cflow_cnet cmeta_cstl
    cmeta_cstl_stream cmeta_simd cmeta_cserde)
  get_target_property(SALTS_VERSION_TARGET_TYPE "${SALTS_VERSION_TARGET}" TYPE)
  if(NOT SALTS_VERSION_TARGET_TYPE STREQUAL "SHARED_LIBRARY")
    continue()
  endif()

  get_target_property(SALTS_FILE_VERSION "${SALTS_VERSION_TARGET}" VERSION)
  set(SALTS_PRODUCT_VERSION "${PROJECT_VERSION}")
  # VERSIONINFO stores four unsigned 16-bit components; absent components are zero.
  foreach(SALTS_VERSION_KIND IN ITEMS FILE PRODUCT)
    string(REPLACE "." ";" SALTS_VERSION_PARTS "${SALTS_${SALTS_VERSION_KIND}_VERSION}")
    list(LENGTH SALTS_VERSION_PARTS SALTS_VERSION_PART_COUNT)
    if(SALTS_VERSION_PART_COUNT LESS 1 OR
       SALTS_VERSION_PART_COUNT GREATER SALTS_VERSION_COMPONENT_COUNT)
      message(FATAL_ERROR "${SALTS_VERSION_TARGET}: invalid ${SALTS_VERSION_KIND} resource version")
    endif()
    foreach(SALTS_VERSION_PART IN LISTS SALTS_VERSION_PARTS)
      if(NOT SALTS_VERSION_PART MATCHES "^(0|[1-9][0-9]*)$" OR
         SALTS_VERSION_PART GREATER SALTS_VERSION_COMPONENT_MAX)
        message(FATAL_ERROR
          "${SALTS_VERSION_TARGET}: invalid ${SALTS_VERSION_KIND} version component '${SALTS_VERSION_PART}'")
      endif()
    endforeach()
    while(SALTS_VERSION_PART_COUNT LESS SALTS_VERSION_COMPONENT_COUNT)
      list(APPEND SALTS_VERSION_PARTS 0)
      list(LENGTH SALTS_VERSION_PARTS SALTS_VERSION_PART_COUNT)
    endwhile()
    list(JOIN SALTS_VERSION_PARTS "," SALTS_${SALTS_VERSION_KIND}_VERSION_NUMBER)
    list(JOIN SALTS_VERSION_PARTS "." SALTS_${SALTS_VERSION_KIND}_VERSION_STRING)
  endforeach()

  get_target_property(SALTS_VERSION_COMPONENT "${SALTS_VERSION_TARGET}" EXPORT_NAME)
  set(SALTS_VERSION_RESOURCE
      "${CMAKE_CURRENT_BINARY_DIR}/version/${SALTS_VERSION_TARGET}-$<CONFIG>.rc")
  configure_file("${CMAKE_CURRENT_LIST_DIR}/SaltsVersion.rc.in"
    "${CMAKE_CURRENT_BINARY_DIR}/version/${SALTS_VERSION_TARGET}.rc.in"
    @ONLY ESCAPE_QUOTES)
  # Resolve the final filename after OUTPUT_NAME and configuration postfixes.
  file(GENERATE OUTPUT "${SALTS_VERSION_RESOURCE}"
    INPUT "${CMAKE_CURRENT_BINARY_DIR}/version/${SALTS_VERSION_TARGET}.rc.in"
    TARGET "${SALTS_VERSION_TARGET}")
  target_sources("${SALTS_VERSION_TARGET}" PRIVATE "${SALTS_VERSION_RESOURCE}")
endforeach()
