#ifndef CONTAINER_BPLUS_TREE_H
#define CONTAINER_BPLUS_TREE_H

#define TURBO_BPLUS_TREE_H CONTAINER_BPLUS_TREE_INTERNAL_H
#define TURBO_BPLUS_TREE_DEFAULT_MIN_DEGREE CONTAINER_BPLUS_TREE_DEFAULT_MIN_DEGREE
#define TURBO_BPLUS_TREE_ALIGNOF CONTAINER_BPLUS_TREE_ALIGNOF
#define turbo_bplus_tree_compare_fn container_bplus_tree_compare_fn
#define turbo_bplus_tree_node_t container_bplus_tree_node_t
#define turbo_bplus_tree_max_align container_bplus_tree_max_align
#define turbo_bplus_tree_max_align_t container_bplus_tree_max_align_t
#define turbo_bplus_tree_t container_bplus_tree_t
#define turbo_bplus_tree_align_up container_bplus_tree_align_up
#define turbo_bplus_tree_is_valid container_bplus_tree_is_valid
#define turbo_bplus_tree_node_key_index_offset container_bplus_tree_node_key_index_offset
#define turbo_bplus_tree_node_value_index_offset container_bplus_tree_node_value_index_offset
#define turbo_bplus_tree_node_key container_bplus_tree_node_key
#define turbo_bplus_tree_node_value container_bplus_tree_node_value
#define turbo_bplus_tree_node_destroy container_bplus_tree_node_destroy
#define turbo_bplus_tree_node_alloc container_bplus_tree_node_alloc
#define turbo_bplus_tree_init_with_order container_bplus_tree_init_with_order
#define turbo_bplus_tree_init container_bplus_tree_init
#define turbo_bplus_tree_destroy container_bplus_tree_destroy
#define turbo_bplus_tree_clear container_bplus_tree_clear
#define turbo_bplus_tree_reserve container_bplus_tree_reserve
#define turbo_bplus_tree_size container_bplus_tree_size
#define turbo_bplus_tree_capacity container_bplus_tree_capacity
#define turbo_bplus_tree_empty container_bplus_tree_empty
#define turbo_bplus_tree_lower_bound container_bplus_tree_lower_bound
#define turbo_bplus_tree_search_leaf container_bplus_tree_search_leaf
#define turbo_bplus_tree_leftmost_leaf container_bplus_tree_leftmost_leaf
#define turbo_bplus_tree_parent_insert container_bplus_tree_parent_insert
#define turbo_bplus_tree_split_child container_bplus_tree_split_child
#define turbo_bplus_tree_put container_bplus_tree_put
#define turbo_bplus_tree_get container_bplus_tree_get
#define turbo_bplus_tree_get_const container_bplus_tree_get_const
#define turbo_bplus_tree_contains container_bplus_tree_contains
#define turbo_bplus_tree_key_at container_bplus_tree_key_at
#define turbo_bplus_tree_key_at_const container_bplus_tree_key_at_const
#define turbo_bplus_tree_value_at container_bplus_tree_value_at
#define turbo_bplus_tree_value_at_const container_bplus_tree_value_at_const
#define turbo_bplus_tree_find_slot container_bplus_tree_find_slot
#define turbo_bplus_tree_remove_rebuild container_bplus_tree_remove_rebuild
#define turbo_bplus_tree_remove container_bplus_tree_remove

#include "../../../turbo/include/turbo_bplus_tree.h"

#endif /* CONTAINER_BPLUS_TREE_H */
