"""Generate IDNA-specific mappings/context predicates from pinned Unicode 17 files."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "unicode/data/17.0.0"
HASHES = {
    "IdnaMappingTable.txt": "87f05505dc026fdb2bff16132bdc68a8014675836882a9a2b1844540ad3be382",
    "DerivedJoiningType.txt": "f39ebe974825d6736aee15582250307aa532b2cfab3caf3f86bd23fddc9c5c4d",
    "Scripts.txt": "9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf",
    "IdnaTestV2.txt": "beb5d0be20e896189b03209a82fdc34f06351502bbd4b8e2523583fc2954d9cf",
}


def rows(name):
    for line in (DATA / name).read_text(encoding="utf-8").splitlines():
        f = [x.strip() for x in line.split("#")[0].split(";")]
        if len(f) > 1:
            bounds = [int(x, 16) for x in f[0].split("..")]
            yield bounds[0], bounds[-1], f[1:]


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, digest in HASHES.items():
        if hashlib.sha256((DATA / name).read_bytes()).hexdigest() != digest:
            raise SystemExit(f"Unicode 17 input hash mismatch: {name}")
    lines = ["/* Generated by idna/tools/generate_idna_data.py; Unicode 17, UTS #46 rev 35.",
             " * Data license: unicode/data/LICENSE.txt.",
             *(f" * {name} SHA-256: {digest}" for name, digest in HASHES.items()), " */"]
    statuses = {"valid": 0, "mapped": 1, "ignored": 2, "deviation": 3, "disallowed": 4}
    values, mappings = [], []
    previous = -1
    for first, last, fields in rows("IdnaMappingTable.txt"):
        assert first == previous + 1
        previous = last
        seq = [int(x, 16) for x in fields[1].split()] if len(fields) > 1 else []
        mappings.append((first, last, len(values), len(seq), statuses[fields[0]]))
        values.extend(seq)
    assert previous == 0x10ffff
    lines += ["static const uint32_t idna_mapping_values[] = {",
              *(f"  0x{x:x}u," for x in values), "};",
              "static const idna_mapping idna_mappings[] = {",
              *(f"  {{0x{a:x}u, 0x{b:x}u, {o}u, {n}u, {s}u}}," for a,b,o,n,s in mappings), "};"]
    props = {}
    # Packed predicates needed by RFC 5892, not a second general Unicode API.
    joining = {"U": 0, "L": 1, "R": 2, "D": 3, "T": 4, "C": 5}
    for a, b, f in rows("DerivedJoiningType.txt"):
        for cp in range(a, b + 1):
            props[cp] = joining[f[0]]
    scripts = {"Greek": 8, "Hebrew": 16, "Hiragana": 32, "Katakana": 32, "Han": 32}
    for a, b, f in rows("Scripts.txt"):
        if f[0] in scripts:
            for cp in range(a, b + 1):
                props[cp] = props.get(cp, 0) | scripts[f[0]]
    ranges = []
    for cp, prop in sorted(props.items()):
        if not prop:
            continue
        if ranges and ranges[-1][1] + 1 == cp and ranges[-1][2] == prop:
            ranges[-1] = (ranges[-1][0], cp, prop)
        else:
            ranges.append((cp, cp, prop))
    lines += ["static const idna_context_range idna_contexts[] = {",
              *(f"  {{0x{a:x}u, 0x{b:x}u, {v}u}}," for a,b,v in ranges), "};", ""]
    result = "\n".join(lines)
    path = ROOT / "idna/src/idna_data.h"
    path.parent.mkdir(parents=True, exist_ok=True)
    if args.check:
        if path.read_text(encoding="ascii") != result:
            raise SystemExit("Stale IDNA tables")
    else:
        path.write_text(result, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
